'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Mobi_DefaultGauge

    '''<summary>
    '''lblGaugeCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGaugeCompanyName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hypFire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypFire As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypBoiler control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypBoiler As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypInfrared control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypInfrared As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypJuris control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypJuris As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypWind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypWind As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypFlood control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypFlood As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypSeismic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypSeismic As Global.System.Web.UI.WebControls.HyperLink
End Class
