
Public Class PSMeta
    Inherits Meta

    Private _Util As ImportUtility

    Public Sub New(pImportUtil As ImportUtility)
        _Util = pImportUtil
    End Sub


    Friend Overrides ReadOnly Property Practice As Libraries.CoreLib.UtilPractice.PracticeEnum
        Get
            Return UtilPractice.PracticeEnum.ProcessSafety
        End Get
    End Property

    Friend Overrides ReadOnly Property SurveyDateCellAddress As CellAddress
        Get
            Return New CellAddress("Rec Tracking", "L4")
        End Get
    End Property

    Friend Overrides ReadOnly Property FileNoCellAddress As CellAddress
        Get
            Return New CellAddress("Rec Tracking", "L3")
        End Get

    End Property

    Friend ReadOnly Property PSRecommendationErrorAddresses As List(Of CellAddress)
        Get
            Dim zList As New List(Of CellAddress)
            zList.Add(New CellAddress("Rec Tracking", "BM2"))
            Return zList
        End Get
    End Property

    Friend Overrides ReadOnly Property TemplateVersionAddress As CellAddress
        Get
            Return New CellAddress("Cope Data", "O7")
        End Get
    End Property


#Region "Standard Import Ranges"


    Overridable ReadOnly Property PSRecTrackingImportInfo As PSImportInfo
        Get
            Return New PSImportInfo(ImportEnum.ImportSheet.RecTracking, ImportEnum.ImportTable.PSRecommendation, {"O8:AG37"}, Me)
        End Get
    End Property

    Overridable ReadOnly Property PSRecTracking2ImportInfo As PSImportInfo
        Get
            Return New PSImportInfo(ImportEnum.ImportSheet.RecTracking, "Rec Tracking (2)", ImportEnum.ImportTable.PSRecommendation, {"O8:AG37"}, Me)
        End Get
    End Property

    Overridable ReadOnly Property PSRecTracking3ImportInfo As PSImportInfo
        Get
            Return New PSImportInfo(ImportEnum.ImportSheet.RecTracking, "Rec Tracking (3)", ImportEnum.ImportTable.PSRecommendation, {"O8:AG37"}, Me)
        End Get
    End Property

    Overridable ReadOnly Property PSRecTracking4ImportInfo As PSImportInfo
        Get
            Return New PSImportInfo(ImportEnum.ImportSheet.RecTracking, "Rec Tracking (4)", ImportEnum.ImportTable.PSRecommendation, {"O8:AG37"}, Me)
        End Get
    End Property

#End Region


#Region "Map Collections"  '(Generated On: 8/27/2012)

    '--AutoGenerated (SQL Table: PSRecommendations)
    Overridable ReadOnly Property PSRecommendationMapCollection As MapCollection
        Get
            Dim zMap As New MapCollection
            With zMap
                .Add("StatusDate", "Date")
                .Add("FileNo", "FileNo")
                .Add("RecYear", "Year")
                .Add("RecMonth", "Month")
                .Add("RecNumber", "No")
                .Add("RecSubletter", "Letter")
                .Add("RecCategory", "Impact")
                ' .Add("Hazard", "Hazard")
                .Add("PrimaryRecType", "Primary")
                .Add("SecondaryRecType", "Secondary")
                .Add("RecKeyWords", "Recommendation Key Words")
                .Add("LossExpectancyBefore", "Current Loss Estimate ($US)")
                .Add("LossExpectancyAfter", "Completed Loss Estimated ($US)")
                .Add("CostToComplete", "Est. Cost to Complete ($US)")
                .Add("SavingsRatio", "Savings Ratio")
                .Add("IntendedAction", "Intended Action")
                .Add("ExpectedCompletionDate", "Expected Completion Date")
                .Add("RecStatus", "Recommendation Tracking Status")
                .Add("CostToCompleteActual", "Actual Cost to Complete")
            End With
            Return zMap
        End Get
    End Property


#End Region


End Class

