'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18063
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GRC.Connect.Web.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DECLARE @tables table (fldName nvarchar(50))
        '''DECLARE @tablename nvarchar(100)
        '''DECLARE @colname nvarchar(100)
        '''DECLARE @insertSQL nvarchar(max)
        '''DECLARE @colSQL nvarchar(max)
        '''DECLARE @valSQL nvarchar(max)
        '''DECLARE @gridIdentity int
        '''DECLARE @sql nvarchar(max)
        '''
        '''INSERT INTO @tables(fldName) values(&apos;tblMetaGrid&apos;)
        '''INSERT INTO @tables(fldName) values(&apos;tblMetaGridColumn&apos;)
        '''
        '''SET @sql = &apos;DECLARE @insertedGridIdentity int, @clonedGridIdentity int&apos; + CHAR(13)+CHAR(10)
        '''SET @sql = @sql + &apos;BEGIN TRANSACTION &apos; + C [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MetaCloneGrid() As String
            Get
                Return ResourceManager.GetString("MetaCloneGrid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT     tblMetaCurrencyConversionFactor.fldId, tblMetaCurrencyConversionFactor.fldClientCurrencyId, fc.fldCode AS fldFromCode, tc.fldCode AS fldToCode, 
        '''                      tblMetaCurrencyConversionFactor.fldExchangeRate
        '''FROM         tblMetaCurrencyConversionFactor INNER JOIN
        '''                      tblMetaCurrency AS tc ON tblMetaCurrencyConversionFactor.fldCurrencyIdTo = tc.fldId INNER JOIN
        '''                      tblMetaCurrency AS fc ON tblMetaCurrencyConversionFactor.fldCurrencyIdFrom = fc.fldId.
        '''</summary>
        Friend ReadOnly Property MetaGetCurrencyView() As String
            Get
                Return ResourceManager.GetString("MetaGetCurrencyView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT    tblMetaLossEstimate.fldId, tblMetaLossEstimate.fldClientCurrencyId, tblMetaLossEstimate.fldCurrencyId, tblMetaLossEstimate.fldLossEstimateTypeId, 
        '''                      tblMetaLossEstimate.fldIndexNo, tblMetaLossEstimate.fldRangeText, tblMetaLossEstimate.fldRangeDisplay, tblMetaLossEstimate.fldRangeValueLow, 
        '''                      tblMetaLossEstimate.fldRangeValueHigh, tblMetaCurrency.fldCode
        '''FROM         tblMetaLossEstimate INNER JOIN
        '''                      tblMetaCurrency ON tblMetaLossEstima [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MetaGetLossEstAfterView() As String
            Get
                Return ResourceManager.GetString("MetaGetLossEstAfterView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT    tblMetaLossEstimate.fldId, tblMetaLossEstimate.fldClientCurrencyId, tblMetaLossEstimate.fldCurrencyId, tblMetaLossEstimate.fldLossEstimateTypeId, 
        '''                      tblMetaLossEstimate.fldIndexNo, tblMetaLossEstimate.fldRangeText, tblMetaLossEstimate.fldRangeDisplay, tblMetaLossEstimate.fldRangeValueLow, 
        '''                      tblMetaLossEstimate.fldRangeValueHigh, tblMetaCurrency.fldCode
        '''FROM         tblMetaLossEstimate INNER JOIN
        '''                      tblMetaCurrency ON tblMetaLossEstima [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MetaGetLossEstBeforeView() As String
            Get
                Return ResourceManager.GetString("MetaGetLossEstBeforeView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT    tblMetaLossEstimate.fldId, tblMetaLossEstimate.fldClientCurrencyId, tblMetaLossEstimate.fldCurrencyId, tblMetaLossEstimate.fldLossEstimateTypeId, 
        '''                      tblMetaLossEstimate.fldIndexNo, tblMetaLossEstimate.fldRangeText, tblMetaLossEstimate.fldRangeDisplay, tblMetaLossEstimate.fldRangeValueLow, 
        '''                      tblMetaLossEstimate.fldRangeValueHigh, tblMetaCurrency.fldCode
        '''FROM         tblMetaLossEstimate INNER JOIN
        '''                      tblMetaCurrency ON tblMetaLossEstima [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MetaGetLossEstCostView() As String
            Get
                Return ResourceManager.GetString("MetaGetLossEstCostView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select * from 
        '''(
        '''Select g.fldId, v.name as source, m.definition,  g.fldGridName as GridName, g.fldGridPageTitle as GridTitle, c.name as field from sys.columns c INNER JOIN
        '''SYS.views v ON c.object_id=v.object_id	INNER JOIN
        '''SYS.sql_modules m ON v.object_id=m.object_id INNER JOIN
        '''tblMetaSource s ON s.fldObjectName=v.name 
        '''INNER JOIN
        '''tblMetaGrid g ON g.fldsourceid=s.fldId
        ''') a
        '''ORDER BY source.
        '''</summary>
        Friend ReadOnly Property MetaGetSourceViewQuery() As String
            Get
                Return ResourceManager.GetString("MetaGetSourceViewQuery", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
