'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GRC.Connect.Libraries.SFTPLib.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property WinSCPexe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("WinSCPexe", resourceCulture)
                Return CType(obj, Byte())
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to [Configuration]
        '''
        '''[Configuration\Interface\Updates]
        '''DotNetVersion=593
        '''Period=0
        '''LastCheck=000000000000F03F
        '''HaveResults=0
        '''ShownResults=0
        '''BetaVersions=2
        '''ShowOnStartup=1
        '''AuthenticationEmail=
        '''ConnectionType=1
        '''ProxyHost=
        '''ProxyPort=8080
        '''ForVersion=0
        '''Version=0
        '''Message=
        '''Critical=0
        '''Release=
        '''Disabled=0
        '''Url=
        '''UrlButton=
        '''NewsUrl=
        '''NewsWidth=0
        '''NewsHeight=0
        '''DownloadUrl=
        '''DownloadSize=0
        '''DownloadSha256=
        '''AuthenticationError=
        '''OpenGettingStarted=0
        '''DownloadingUrl=
        '''TipsWidth=0
        '''TipsHeight=0
        '''TipsUrl=
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property WinSCPIni() As String
            Get
                Return ResourceManager.GetString("WinSCPIni", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
