'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SwitchIntegrated

    '''<summary>
    '''RadScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager

    '''<summary>
    '''divMainListContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMainListContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSwitchTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSwitchTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divSwitchCellContainerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSwitchCellContainerName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divSwitchColumn1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSwitchColumn1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptSwitchCol1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSwitchCol1 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''divSwitchColumn2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSwitchColumn2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptSwitchCol2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSwitchCol2 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''divSwitchColumn3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSwitchColumn3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptSwitchCol3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSwitchCol3 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''divSwitchColumn4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSwitchColumn4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptSwitchCol4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSwitchCol4 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''divSwitchColumn5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSwitchColumn5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptSwitchCol5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSwitchCol5 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''divSwitchColumn6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSwitchColumn6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptSwitchCol6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSwitchCol6 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''divSwitchCellContainerFilePrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSwitchCellContainerFilePrefix As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divSwitchFilePrefixColumn1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSwitchFilePrefixColumn1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptSwitchFilePrefixCol1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSwitchFilePrefixCol1 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''divSwitchFilePrefixColumn2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSwitchFilePrefixColumn2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptSwitchFilePrefixCol2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSwitchFilePrefixCol2 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''divSwitchFilePrefixColumn3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSwitchFilePrefixColumn3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptSwitchFilePrefixCol3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSwitchFilePrefixCol3 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''divSwitchFilePrefixColumn4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSwitchFilePrefixColumn4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptSwitchFilePrefixCol4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSwitchFilePrefixCol4 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''divSwitchFilePrefixColumn5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSwitchFilePrefixColumn5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptSwitchFilePrefixCol5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSwitchFilePrefixCol5 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''divSwitchFilePrefixColumn6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSwitchFilePrefixColumn6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptSwitchFilePrefixCol6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSwitchFilePrefixCol6 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''txtWelcome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWelcome As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divSecondaryLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSecondaryLogo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divSideGraphic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSideGraphic As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divComboContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divComboContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divSecondaryTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSecondaryTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divSecondaryExtraPadding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSecondaryExtraPadding As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divSecondaryInstructions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSecondaryInstructions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cboClientByName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboClientByName As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cboClientByFilePrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboClientByFilePrefix As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''divSecondaryEnterButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSecondaryEnterButton As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnSkip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSkip As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divSecondaryNotice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSecondaryNotice As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divThirdEnterButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divThirdEnterButtons As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnSkip2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSkip2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''spnButtonSpace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnButtonSpace As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNext As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divPreferences control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPreferences As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''chkEditPreferences control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEditPreferences As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''hypChangePassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypChangePassword As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''divLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLinks As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hypGRCConnectTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypGRCConnectTest As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypGRCConnectLive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypGRCConnectLive As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hypSystemTools control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hypSystemTools As Global.System.Web.UI.WebControls.HyperLink
End Class
