var dsAdminWindowUserActivity = {
    "isSuccess": true,
    "message": null,
    "data": {
        "users": [
            {
                "colLoginID": 0,
                "colEzyUserID": 0,
                "colFullName": "",
                "colUserID": "",
                "colPassword": "",
                "colDateTimeStamp": "1/1/1900",
                "colLastLogin": "1/1/1900",
                "colActiveUser": false,
                "colThirdParty": false,
                "colInternal": false,
                "colGrcadministrator": "",
                "colRiskManager": false,
                "colDocumentAccess": false,
                "colCustomAccess": false,
                "colCustomAccessText": "",
                "colDivisionManager": false,
                "colDivision": "",
                "colPlantManager": false,
                "colPlant": "",
                "colPhone": "",
                "colFax": "",
                "colEmail": "",
                "colComments": "",
                "colRInit": "",
                "colRReport": "",
                "colRfu1": "",
                "colRfu2": "",
                "colRfu3": "",
                "colROverdue1": "",
                "colROverdue2": "",
                "colROverdue3": "",
                "colExpOverdue": "",
                "colWo": false,
                "colCCActive": false,
                "colOperatorStamp": null,
                "colNotificationStamp": "1/1/1900",
                "colFilePrefix": null,
                "colLastPWChange": "1/1/1900",
                "colRActResp": null,
                "colCalist": null,
                "colDivlist": null,
                "colLoclist": null,
                "colLastRecentUpdate": "1/1/1900",
                "colClientLocNoManager": false,
                "colClientLocNoText": "",
                "colFacilityManager": false,
                "colFacilityText": "",
                "colCityManager": false,
                "colCityText": "",
                "colStProvManager": false,
                "colStProvText": "",
                "colCountryManager": false,
                "colCountryText": "",
                "colRExpd": "",
                "colCCOnly": false,
                "colClientAdministration": false
            }
        ]
    }
};

function buildAdminWindowEmptyUser() {
    return {
        "colLoginID": ko.observable(0),
        "colEzyUserID": ko.observable(0),
        "colFullName": ko.observable(""),
        "colUserID": ko.observable(""),
        "colPassword": ko.observable(""),
        "colDateTimeStamp": ko.observable("1/1/1900"),
        "colLastLogin": ko.observable("1/1/1900"),
        "colActiveUser": ko.observable(false),
        "colThirdParty": ko.observable(false),
        "colInternal": ko.observable(false),
        "colGrcadministrator": ko.observable(""),
        "colRiskManager": ko.observable(false),
        "colDocumentAccess": ko.observable(false),
        "colCustomAccess": ko.observable(false),
        "colCustomAccessText": ko.observable(""),
        "colDivisionManager": ko.observable(false),
        "colDivision": ko.observable(""),
        "colPlantManager": ko.observable(false),
        "colPlant": ko.observable(""),
        "colPhone": ko.observable(""),
        "colFax": ko.observable(""),
        "colEmail": ko.observable(""),
        "colComments": ko.observable(""),
        "colRInit": ko.observable(""),
        "colRReport": ko.observable(""),
        "colRfu1": ko.observable(""),
        "colRfu2": ko.observable(""),
        "colRfu3": ko.observable(""),
        "colROverdue1": ko.observable(""),
        "colROverdue2": ko.observable(""),
        "colROverdue3": ko.observable(""),
        "colExpOverdue": ko.observable(""),
        "colWo": ko.observable(false),
        "colCCActive": ko.observable(false),
        "colOperatorStamp": ko.observable(null),
        "colNotificationStamp": ko.observable(null),
        "colFilePrefix": ko.observable(null),
        "colLastPWChange": ko.observable(null),
        "colRActResp": ko.observable(null),
        "colCalist": ko.observable(null),
        "colDivlist": ko.observable(null),
        "colLoclist": ko.observable(null),
        "colLastRecentUpdate": ko.observable("1/1/1900"),
        "colClientLocNoManager": ko.observable(false),
        "colClientLocNoText": ko.observable(""),
        "colFacilityManager": ko.observable(false),
        "colFacilityText": ko.observable(""),
        "colCityManager": ko.observable(false),
        "colCityText": ko.observable(""),
        "colStProvManager": ko.observable(false),
        "colStProvText": ko.observable(""),
        "colCountryManager": ko.observable(false),
        "colCountryText": ko.observable(""),
        "colRExpd": ko.observable(""),
        "colCCOnly": ko.observable(false),
        "colClientAdministration": ko.observable(false)

    }
}


function buildAdminWindowUserActivityJSON(pQty) {
    var zReturn = {
        "isSuccess": true,
        "message": null,
        "data": {
            "users": []
        }
    }
    var zQty = 10;
    if (pQty) {
        zQty = Number(pQty);
    }
    for (var i = 0; i < zQty; i++) {
        zReturn.data.users.push({
            "colLoginID": i,
            "colEzyUserID": i,
            "colFullName": "Name " + i,
            "colUserID": "",
            "colPassword": "",
            "colDateTimeStamp": "1/1/1900",
            "colLastLogin": "1/1/1900",
            "colActiveUser": false,
            "colThirdParty": false,
            "colInternal": false,
            "colGrcadministrator": "",
            "colRiskManager": false,
            "colDocumentAccess": false,
            "colCustomAccess": false,
            "colCustomAccessText": "",
            "colDivisionManager": false,
            "colDivision": "",
            "colPlantManager": false,
            "colPlant": "",
            "colPhone": "",
            "colFax": "",
            "colEmail": "",
            "colComments": "",
            "colRInit": "",
            "colRReport": "",
            "colRfu1": "",
            "colRfu2": "",
            "colRfu3": "",
            "colROverdue1": "",
            "colROverdue2": "",
            "colROverdue3": "",
            "colExpOverdue": "",
            "colWo": false,
            "colCCActive": false,
            "colOperatorStamp": null,
            "colNotificationStamp": null,
            "colFilePrefix": null,
            "colLastPWChange": null,
            "colRActResp": null,
            "colCalist": null,
            "colDivlist": null,
            "colLoclist": null,
            "colLastRecentUpdate": "1/1/1900",
            "colClientLocNoManager": false,
            "colClientLocNoText": "",
            "colFacilityManager": false,
            "colFacilityText": "",
            "colCityManager": false,
            "colCityText": "",
            "colStProvManager": false,
            "colStProvText": "",
            "colCountryManager": false,
            "colCountryText": "",
            "colRExpd": "",
            "colCCOnly": false,
            "colClientAdministration": false
        });
    }
    return zReturn;
}