'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EmailTemplateEditorControl

    '''<summary>
    '''uxSubjectEditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uxSubjectEditor As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''uxBodyEditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uxBodyEditor As Global.Telerik.Web.UI.RadEditor

    '''<summary>
    '''uxSaveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uxSaveButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''uxCancelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uxCancelButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''uxID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uxID As Global.System.Web.UI.WebControls.HiddenField
End Class
