'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Charts_Recommendations

    '''<summary>
    '''divDrillDownContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDrillDownContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tableHeaderContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tableHeaderContainer As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''cmdAllRecommendations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAllRecommendations As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDivision As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDivisionValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDivisionValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCustomAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomAccess As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCustomAccessValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomAccessValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTIV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTIV As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTIVValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTIVValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdDrillBacks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDrillBacks As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdEmail As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''printCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents printCompanyName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tdAllRecommendations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdAllRecommendations As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdParameters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdParameters As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''trMessageContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trMessageContainer As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''trTipContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trTipContainer As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''trFooterTableContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trFooterTableContainer As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdImpactLegend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdImpactLegend As Global.System.Web.UI.HtmlControls.HtmlTableCell
End Class
