'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class notification

    '''<summary>
    '''divMessage01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMessage01 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divMessage02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMessage02 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divMessage03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMessage03 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
