'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ChartTest01

    '''<summary>
    '''cmdAllRecommendations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAllRecommendations As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDivision As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDivisionValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDivisionValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCustomAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomAccess As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCustomAccessValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomAccessValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTIV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTIV As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTIVValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTIVValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdDrillBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDrillBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdEmail As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdPDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdPDF As Global.System.Web.UI.WebControls.Button
End Class
