var whatIfData = [
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0001",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "531-00",
       "address": "Industriestrasse 35",
       "City": "Lannach",
       "StProv": "",
       "zip": "",
       "Country": "Austria",
       "latitude": 46.9619,
       "longitude": 15.3347,
       "TIV": 848.84,
       "RecYear": 2004,
       "RecMonth": "07",
       "RecNumber": 1,
       "RecSubletter": "A",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-03-12T00:00:00",
       "RecCategory": "High",
       "PrimaryRecType": "Sprinklers",
       "SecondaryRecType": "New Sprinklers",
       "RecKeyWords": "Automatic sprinklers in Main Production Hall.",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 148720000.0,
       "LossExpectancyBefore": "100MM-250MM",
       "LossExpectancyAfterActual": 1918400.0,
       "LossExpectancyAfter": "1MM-5MM",
       "CostToCompleteActual": 2200000.0,
       "CostToComplete": ">1MM",
       "ActualCostToComplete": null,
       "SavingsRatio": 67.0,
       "IntendedAction": "No Commitment",
       "ResponseDate": "2018-07-11T00:00:00",
       "ResponseFrom": "Kris Kibsey",
       "PlantComment": "We've asked and waiting to see if it is approved.",
       "PlantCommentLineBreak": "We've asked and waiting to see if it is approved.",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "We've asked and waiting to see if it is approved.",
       "StatusDateString": "12 Mar 19",
       "ResponseDateString": "11 Jul 18",
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 3,
       "StatusDateYear": 2019,
       "ResponseDateMonth": 7,
       "ResponseDateYear": 2018,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#FF0000",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 287182,
       "RatingCatPts": "FP 4.64",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 16.70,
       "RecPriority": 3,
       "ROWNUMBER": 1,
       "SortRowNo": 1
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0001",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "531-00",
       "address": "Industriestrasse 35",
       "City": "Lannach",
       "StProv": "",
       "zip": "",
       "Country": "Austria",
       "latitude": 46.9619,
       "longitude": 15.3347,
       "TIV": 848.84,
       "RecYear": 2004,
       "RecMonth": "07",
       "RecNumber": 1,
       "RecSubletter": "C",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-03-12T00:00:00",
       "RecCategory": "High",
       "PrimaryRecType": "Sprinklers",
       "SecondaryRecType": "New Sprinklers",
       "RecKeyWords": "Automatic sprinklers in Hardening and Foundry Building.",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 148720000.0,
       "LossExpectancyBefore": "100MM-250MM",
       "LossExpectancyAfterActual": 1918400.0,
       "LossExpectancyAfter": "1MM-5MM",
       "CostToCompleteActual": 154000.0,
       "CostToComplete": "100K-250K",
       "ActualCostToComplete": null,
       "SavingsRatio": 953.0,
       "IntendedAction": "No Commitment",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "12 Mar 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 3,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#FF0000",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 287183,
       "RatingCatPts": "FP 4.64",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 16.70,
       "RecPriority": 2,
       "ROWNUMBER": 2,
       "SortRowNo": 2
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0001",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "531-00",
       "address": "Industriestrasse 35",
       "City": "Lannach",
       "StProv": "",
       "zip": "",
       "Country": "Austria",
       "latitude": 46.9619,
       "longitude": 15.3347,
       "TIV": 848.84,
       "RecYear": 2004,
       "RecMonth": "07",
       "RecNumber": 1,
       "RecSubletter": "D",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-03-12T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "Sprinklers",
       "SecondaryRecType": "New Sprinklers",
       "RecKeyWords": "Automatic sprinklers in other unprotected structures.",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 13992000.0,
       "LossExpectancyBefore": "10MM-25MM",
       "LossExpectancyAfterActual": 405680.0,
       "LossExpectancyAfter": "100K-500K",
       "CostToCompleteActual": 968000.0,
       "CostToComplete": "500K-1MM",
       "ActualCostToComplete": null,
       "SavingsRatio": 14.0,
       "IntendedAction": "No Commitment",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "12 Mar 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 3,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 287184,
       "RatingCatPts": "FP 0.78",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 2.81,
       "RecPriority": 5,
       "ROWNUMBER": 3,
       "SortRowNo": 3
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0001",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "531-00",
       "address": "Industriestrasse 35",
       "City": "Lannach",
       "StProv": "",
       "zip": "",
       "Country": "Austria",
       "latitude": 46.9619,
       "longitude": 15.3347,
       "TIV": 848.84,
       "RecYear": 2004,
       "RecMonth": "07",
       "RecNumber": 1,
       "RecSubletter": "E",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-03-12T00:00:00",
       "RecCategory": "High",
       "PrimaryRecType": "Water Supply",
       "SecondaryRecType": "Water Supply Adeq.",
       "RecKeyWords": "Water supply for automatic protection",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 148720000.0,
       "LossExpectancyBefore": "100MM-250MM",
       "LossExpectancyAfterActual": 1918400.0,
       "LossExpectancyAfter": "1MM-5MM",
       "CostToCompleteActual": 440000.0,
       "CostToComplete": "250K-500K",
       "ActualCostToComplete": null,
       "SavingsRatio": 334.0,
       "IntendedAction": "No Commitment",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "12 Mar 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 3,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#FF0000",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 287185,
       "RatingCatPts": "FP 4.64",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 16.70,
       "RecPriority": 3,
       "ROWNUMBER": 4,
       "SortRowNo": 4
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0001",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "531-00",
       "address": "Industriestrasse 35",
       "City": "Lannach",
       "StProv": "",
       "zip": "",
       "Country": "Austria",
       "latitude": 46.9619,
       "longitude": 15.3347,
       "TIV": 848.84,
       "RecYear": 2011,
       "RecMonth": "12",
       "RecNumber": 1,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-03-12T00:00:00",
       "RecCategory": "High",
       "PrimaryRecType": "Spec. Hazards",
       "SecondaryRecType": "Flam Liq/Gas Handling",
       "RecKeyWords": "Ignitable liquid storage rooms A to C improvement",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 148720000.0,
       "LossExpectancyBefore": "100MM-250MM",
       "LossExpectancyAfterActual": 1425600.0,
       "LossExpectancyAfter": "1MM-5MM",
       "CostToCompleteActual": 110000.0,
       "CostToComplete": "100K-250K",
       "ActualCostToComplete": null,
       "SavingsRatio": 1339.0,
       "IntendedAction": "No Commitment",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "12 Mar 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 3,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#FF0000",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 287186,
       "RatingCatPts": "FP 4.65",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 16.74,
       "RecPriority": 2,
       "ROWNUMBER": 5,
       "SortRowNo": 5
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0001",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "531-00",
       "address": "Industriestrasse 35",
       "City": "Lannach",
       "StProv": "",
       "zip": "",
       "Country": "Austria",
       "latitude": 46.9619,
       "longitude": 15.3347,
       "TIV": 848.84,
       "RecYear": 2014,
       "RecMonth": "03",
       "RecNumber": 1,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-03-12T00:00:00",
       "RecCategory": "Moderate",
       "PrimaryRecType": "Spec. Hazards",
       "SecondaryRecType": "Flam Liq/Gas Handling",
       "RecKeyWords": "Plastic composite IBCs with combustible content.",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 148720000.0,
       "LossExpectancyBefore": "100MM-250MM",
       "LossExpectancyAfterActual": 90640000.0,
       "LossExpectancyAfter": "50MM-100MM",
       "CostToCompleteActual": 44000.0,
       "CostToComplete": "25K-50K",
       "ActualCostToComplete": null,
       "SavingsRatio": 1320.0,
       "IntendedAction": "Will Study",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "12 Mar 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 3,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#FFFF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 287187,
       "RatingCatPts": "FP 1.88",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 6.77,
       "RecPriority": 2,
       "ROWNUMBER": 6,
       "SortRowNo": 6
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0001",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "531-00",
       "address": "Industriestrasse 35",
       "City": "Lannach",
       "StProv": "",
       "zip": "",
       "Country": "Austria",
       "latitude": 46.9619,
       "longitude": 15.3347,
       "TIV": 848.84,
       "RecYear": 2019,
       "RecMonth": "03",
       "RecNumber": 1,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-03-12T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "Human Element",
       "SecondaryRecType": "Storage Configuration",
       "RecKeyWords": "Relocate Tire Storage",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 968000.0,
       "LossExpectancyBefore": "500K-1MM",
       "LossExpectancyAfterActual": 105600.0,
       "LossExpectancyAfter": "100K-500K",
       "CostToCompleteActual": 0.0,
       "CostToComplete": "Maintenance Time",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Will Study",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "12 Mar 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 3,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308195,
       "RatingCatPts": "HE 0.05",
       "RatingCatWeight": 1.60,
       "RatingScoreChange": 0.08,
       "RecPriority": 4,
       "ROWNUMBER": 7,
       "SortRowNo": 7
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0001",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "531-00",
       "address": "Industriestrasse 35",
       "City": "Lannach",
       "StProv": "",
       "zip": "",
       "Country": "Austria",
       "latitude": 46.9619,
       "longitude": 15.3347,
       "TIV": 848.84,
       "RecYear": 2019,
       "RecMonth": "03",
       "RecNumber": 2,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-03-12T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "Human Element",
       "SecondaryRecType": "Emerg. Response",
       "RecKeyWords": "Improve Ignitable Liquid Emergency Response Plans",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 0.0,
       "LossExpectancyBefore": "HE/Reliability",
       "LossExpectancyAfterActual": 0.0,
       "LossExpectancyAfter": "Probability Reduction",
       "CostToCompleteActual": 0.0,
       "CostToComplete": "Maintenance Time",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Will Study",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "12 Mar 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 3,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308194,
       "RatingCatPts": "HE 0.10",
       "RatingCatWeight": 1.60,
       "RatingScoreChange": 0.16,
       "RecPriority": 1,
       "ROWNUMBER": 8,
       "SortRowNo": 8
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0001",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "531-00",
       "address": "Industriestrasse 35",
       "City": "Lannach",
       "StProv": "",
       "zip": "",
       "Country": "Austria",
       "latitude": 46.9619,
       "longitude": 15.3347,
       "TIV": 848.84,
       "RecYear": 2019,
       "RecMonth": "03",
       "RecNumber": 3,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-03-12T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "Human Element",
       "SecondaryRecType": "Hot Work",
       "RecKeyWords": "Hot Work Documentation Improvement",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 0.0,
       "LossExpectancyBefore": "HE/Reliability",
       "LossExpectancyAfterActual": 0.0,
       "LossExpectancyAfter": "Probability Reduction",
       "CostToCompleteActual": 0.0,
       "CostToComplete": "Maintenance Time",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Will Study",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "12 Mar 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 3,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308193,
       "RatingCatPts": "HE 0.30",
       "RatingCatWeight": 1.60,
       "RatingScoreChange": 0.48,
       "RecPriority": 1,
       "ROWNUMBER": 9,
       "SortRowNo": 9
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0007",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1721-01",
       "address": "Avenida Finsa 1521",
       "City": "Guadalupe",
       "StProv": "NLE",
       "zip": "67114",
       "Country": "Mexico",
       "latitude": 25.6945,
       "longitude": -100.1316,
       "TIV": 23.99,
       "RecYear": 2017,
       "RecMonth": "05",
       "RecNumber": 1,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-03-06T00:00:00",
       "RecCategory": "High",
       "PrimaryRecType": "Sprinklers",
       "SecondaryRecType": "New Sprinklers",
       "RecKeyWords": "Install Fire Sprinkler Systems",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 29100000.0,
       "LossExpectancyBefore": "25MM-50MM",
       "LossExpectancyAfterActual": 558000.0,
       "LossExpectancyAfter": "500K-1MM",
       "CostToCompleteActual": 250000.0,
       "CostToComplete": "100K-250K",
       "ActualCostToComplete": null,
       "SavingsRatio": 114.0,
       "IntendedAction": "No Commitment",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "06 Mar 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 3,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#FF0000",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308930,
       "RatingCatPts": "FP 9.86",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 35.50,
       "RecPriority": 5,
       "ROWNUMBER": 10,
       "SortRowNo": 10
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0007",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1721-01",
       "address": "Avenida Finsa 1521",
       "City": "Guadalupe",
       "StProv": "NLE",
       "zip": "67114",
       "Country": "Mexico",
       "latitude": 25.6945,
       "longitude": -100.1316,
       "TIV": 23.99,
       "RecYear": 2017,
       "RecMonth": "05",
       "RecNumber": 2,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-03-06T00:00:00",
       "RecCategory": "High",
       "PrimaryRecType": "Water Supply",
       "SecondaryRecType": "Water Supply Adeq.",
       "RecKeyWords": "Provide an Adequate Water Supply",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 29100000.0,
       "LossExpectancyBefore": "25MM-50MM",
       "LossExpectancyAfterActual": 558000.0,
       "LossExpectancyAfter": "500K-1MM",
       "CostToCompleteActual": 175000.0,
       "CostToComplete": "100K-250K",
       "ActualCostToComplete": null,
       "SavingsRatio": 163.0,
       "IntendedAction": "No Commitment",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "06 Mar 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 3,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#FF0000",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308929,
       "RatingCatPts": "FP 9.86",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 35.50,
       "RecPriority": 5,
       "ROWNUMBER": 11,
       "SortRowNo": 11
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0007",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1721-01",
       "address": "Avenida Finsa 1521",
       "City": "Guadalupe",
       "StProv": "NLE",
       "zip": "67114",
       "Country": "Mexico",
       "latitude": 25.6945,
       "longitude": -100.1316,
       "TIV": 23.99,
       "RecYear": 2017,
       "RecMonth": "05",
       "RecNumber": 5,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-03-06T00:00:00",
       "RecCategory": "High",
       "PrimaryRecType": "Human Element",
       "SecondaryRecType": "Sprink/Supply Testing",
       "RecKeyWords": "Conduct Peformance Test of Fire Pump",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 0.0,
       "LossExpectancyBefore": "HE/Reliability",
       "LossExpectancyAfterActual": 0.0,
       "LossExpectancyAfter": "Probability Reduction",
       "CostToCompleteActual": 0.0,
       "CostToComplete": "Maintenance Time",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Will Study",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "06 Mar 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 3,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#FF0000",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308931,
       "RatingCatPts": "HE 3.70",
       "RatingCatWeight": 1.60,
       "RatingScoreChange": 5.92,
       "RecPriority": 1,
       "ROWNUMBER": 12,
       "SortRowNo": 12
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0007",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1721-01",
       "address": "Avenida Finsa 1521",
       "City": "Guadalupe",
       "StProv": "NLE",
       "zip": "67114",
       "Country": "Mexico",
       "latitude": 25.6945,
       "longitude": -100.1316,
       "TIV": 23.99,
       "RecYear": 2017,
       "RecMonth": "05",
       "RecNumber": 8,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-03-06T00:00:00",
       "RecCategory": "Moderate",
       "PrimaryRecType": "Human Element",
       "SecondaryRecType": "Self-Inspections",
       "RecKeyWords": "Create a Valve Inspection Program",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 0.0,
       "LossExpectancyBefore": "HE/Reliability",
       "LossExpectancyAfterActual": 0.0,
       "LossExpectancyAfter": "Probability Reduction",
       "CostToCompleteActual": 0.0,
       "CostToComplete": "Maintenance Time",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Will Study",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "06 Mar 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 3,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#FFFF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308932,
       "RatingCatPts": "HE 2.00",
       "RatingCatWeight": 1.60,
       "RatingScoreChange": 3.20,
       "RecPriority": 1,
       "ROWNUMBER": 13,
       "SortRowNo": 13
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0007",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1721-01",
       "address": "Avenida Finsa 1521",
       "City": "Guadalupe",
       "StProv": "NLE",
       "zip": "67114",
       "Country": "Mexico",
       "latitude": 25.6945,
       "longitude": -100.1316,
       "TIV": 23.99,
       "RecYear": 2017,
       "RecMonth": "05",
       "RecNumber": 10,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-03-06T00:00:00",
       "RecCategory": "Moderate",
       "PrimaryRecType": "Surveillance",
       "SecondaryRecType": "Fire Prot. Supv.",
       "RecKeyWords": "Lock Fire Protection Valves in the Open Position",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 0.0,
       "LossExpectancyBefore": "HE/Reliability",
       "LossExpectancyAfterActual": 0.0,
       "LossExpectancyAfter": "Probability Reduction",
       "CostToCompleteActual": 0.0,
       "CostToComplete": "Maintenance Time",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Will Study",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "06 Mar 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 3,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#FFFF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308933,
       "RatingCatPts": "FP 0.75",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 2.70,
       "RecPriority": 1,
       "ROWNUMBER": 14,
       "SortRowNo": 14
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0007",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1721-01",
       "address": "Avenida Finsa 1521",
       "City": "Guadalupe",
       "StProv": "NLE",
       "zip": "67114",
       "Country": "Mexico",
       "latitude": 25.6945,
       "longitude": -100.1316,
       "TIV": 23.99,
       "RecYear": 2019,
       "RecMonth": "03",
       "RecNumber": 1,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-03-06T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "Spec. Hazards",
       "SecondaryRecType": "Bldg Materials",
       "RecKeyWords": "Fire Separation",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 2260000.0,
       "LossExpectancyBefore": "1MM-5MM",
       "LossExpectancyAfterActual": 564000.0,
       "LossExpectancyAfter": "500K-1MM",
       "CostToCompleteActual": 30000.0,
       "CostToComplete": "25K-50K",
       "ActualCostToComplete": null,
       "SavingsRatio": 57.0,
       "IntendedAction": "No Commitment",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "06 Mar 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 3,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308934,
       "RatingCatPts": "FP 0.64",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 2.30,
       "RecPriority": 3,
       "ROWNUMBER": 15,
       "SortRowNo": 15
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0007",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1721-01",
       "address": "Avenida Finsa 1521",
       "City": "Guadalupe",
       "StProv": "NLE",
       "zip": "67114",
       "Country": "Mexico",
       "latitude": 25.6945,
       "longitude": -100.1316,
       "TIV": 23.99,
       "RecYear": 2019,
       "RecMonth": "03",
       "RecNumber": 2,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-03-06T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "Surveillance",
       "SecondaryRecType": "Smoke/Heat Det.",
       "RecKeyWords": "Install Smoke Detection in Electrical Rooms",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 214000.0,
       "LossExpectancyBefore": "100K-500K",
       "LossExpectancyAfterActual": 25000.0,
       "LossExpectancyAfter": "<50K",
       "CostToCompleteActual": 10000.0,
       "CostToComplete": "5K-10K",
       "ActualCostToComplete": null,
       "SavingsRatio": 19.0,
       "IntendedAction": "No Commitment",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "06 Mar 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 3,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308936,
       "RatingCatPts": "FP 0.07",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 0.25,
       "RecPriority": 2,
       "ROWNUMBER": 16,
       "SortRowNo": 16
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0007",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1721-01",
       "address": "Avenida Finsa 1521",
       "City": "Guadalupe",
       "StProv": "NLE",
       "zip": "67114",
       "Country": "Mexico",
       "latitude": 25.6945,
       "longitude": -100.1316,
       "TIV": 23.99,
       "RecYear": 2019,
       "RecMonth": "03",
       "RecNumber": 3,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-03-06T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "Human Element",
       "SecondaryRecType": "Other HE",
       "RecKeyWords": "IT Room Improvements",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 0.0,
       "LossExpectancyBefore": "HE/Reliability",
       "LossExpectancyAfterActual": 0.0,
       "LossExpectancyAfter": "Probability Reduction",
       "CostToCompleteActual": 0.0,
       "CostToComplete": "Maintenance Time",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Will Study",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "06 Mar 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 3,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308937,
       "RatingCatPts": "HE 0.10",
       "RatingCatWeight": 1.60,
       "RatingScoreChange": 0.16,
       "RecPriority": 1,
       "ROWNUMBER": 17,
       "SortRowNo": 17
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0007",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1721-01",
       "address": "Avenida Finsa 1521",
       "City": "Guadalupe",
       "StProv": "NLE",
       "zip": "67114",
       "Country": "Mexico",
       "latitude": 25.6945,
       "longitude": -100.1316,
       "TIV": 23.99,
       "RecYear": 2019,
       "RecMonth": "02",
       "RecNumber": 4,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-03-06T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "BCP",
       "SecondaryRecType": "BCP/DRP",
       "RecKeyWords": "Develop a Business Continuity Plan",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 0.0,
       "LossExpectancyBefore": "HE/Reliability",
       "LossExpectancyAfterActual": 0.0,
       "LossExpectancyAfter": "Probability Reduction",
       "CostToCompleteActual": 0.0,
       "CostToComplete": "Maintenance Time",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Will Study",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "06 Mar 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 3,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308935,
       "RatingCatPts": "BCP 7.00",
       "RatingCatWeight": 0.30,
       "RatingScoreChange": 2.10,
       "RecPriority": 3,
       "ROWNUMBER": 18,
       "SortRowNo": 18
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0008",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1588-00",
       "address": "Avenida Jorge Sachs, 650",
       "City": "Sao Joaquim de Bicas,",
       "StProv": "MG",
       "zip": "32920-000",
       "Country": "Brazil",
       "latitude": -20.0546,
       "longitude": -44.2749,
       "TIV": 51.4,
       "RecYear": 2012,
       "RecMonth": "05",
       "RecNumber": 1,
       "RecSubletter": "B",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-04-04T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "Water Supply",
       "SecondaryRecType": "Water Supply Adeq.",
       "RecKeyWords": "Adequate Fire Protection Water Supply, Mains & Hydrants",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 1340000.0,
       "LossExpectancyBefore": "1MM-5MM",
       "LossExpectancyAfterActual": 249000.0,
       "LossExpectancyAfter": "100K-500K",
       "CostToCompleteActual": 750000.0,
       "CostToComplete": "500K-1MM",
       "ActualCostToComplete": null,
       "SavingsRatio": 1.0,
       "IntendedAction": "No Commitment",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "04 Apr 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 4,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308870,
       "RatingCatPts": "FP 0.81",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 2.92,
       "RecPriority": 1,
       "ROWNUMBER": 19,
       "SortRowNo": 19
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0008",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1588-00",
       "address": "Avenida Jorge Sachs, 650",
       "City": "Sao Joaquim de Bicas,",
       "StProv": "MG",
       "zip": "32920-000",
       "Country": "Brazil",
       "latitude": -20.0546,
       "longitude": -44.2749,
       "TIV": 51.4,
       "RecYear": 2012,
       "RecMonth": "05",
       "RecNumber": 3,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-04-04T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "Spec. Hazards",
       "SecondaryRecType": "Other Spec. Hazards",
       "RecKeyWords": "Powder Coating Improvements.  ",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 1340000.0,
       "LossExpectancyBefore": "1MM-5MM",
       "LossExpectancyAfterActual": 245000.0,
       "LossExpectancyAfter": "100K-500K",
       "CostToCompleteActual": 15000.0,
       "CostToComplete": "10K-25K",
       "ActualCostToComplete": null,
       "SavingsRatio": 73.0,
       "IntendedAction": "Will Study",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "04 Apr 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 4,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308876,
       "RatingCatPts": "FP 0.21",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 0.76,
       "RecPriority": 2,
       "ROWNUMBER": 20,
       "SortRowNo": 20
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0008",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1588-00",
       "address": "Avenida Jorge Sachs, 650",
       "City": "Sao Joaquim de Bicas,",
       "StProv": "MG",
       "zip": "32920-000",
       "Country": "Brazil",
       "latitude": -20.0546,
       "longitude": -44.2749,
       "TIV": 51.4,
       "RecYear": 2012,
       "RecMonth": "05",
       "RecNumber": 5,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-04-04T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "Spec. Hazards",
       "SecondaryRecType": "Fire Separation",
       "RecKeyWords": "Electrical Substation Improvements.  ",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 911000.0,
       "LossExpectancyBefore": "500K-1MM",
       "LossExpectancyAfterActual": 142000.0,
       "LossExpectancyAfter": "100K-500K",
       "CostToCompleteActual": 50000.0,
       "CostToComplete": "25K-50K",
       "ActualCostToComplete": null,
       "SavingsRatio": 15.0,
       "IntendedAction": "Will Study",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "04 Apr 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 4,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308873,
       "RatingCatPts": "FP 0.29",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 1.04,
       "RecPriority": 2,
       "ROWNUMBER": 21,
       "SortRowNo": 21
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0008",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1588-00",
       "address": "Avenida Jorge Sachs, 650",
       "City": "Sao Joaquim de Bicas,",
       "StProv": "MG",
       "zip": "32920-000",
       "Country": "Brazil",
       "latitude": -20.0546,
       "longitude": -44.2749,
       "TIV": 51.4,
       "RecYear": 2012,
       "RecMonth": "05",
       "RecNumber": 6,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-04-04T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "Spec. Hazards",
       "SecondaryRecType": "Other Spec. Hazards",
       "RecKeyWords": "Automatic Shutdown for Hydraulic Presses.",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 1340000.0,
       "LossExpectancyBefore": "1MM-5MM",
       "LossExpectancyAfterActual": 245000.0,
       "LossExpectancyAfter": "100K-500K",
       "CostToCompleteActual": 20000.0,
       "CostToComplete": "10K-25K",
       "ActualCostToComplete": null,
       "SavingsRatio": 55.0,
       "IntendedAction": "Will Study",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "04 Apr 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 4,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308877,
       "RatingCatPts": "FP 0.21",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 0.76,
       "RecPriority": 2,
       "ROWNUMBER": 22,
       "SortRowNo": 22
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0008",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1588-00",
       "address": "Avenida Jorge Sachs, 650",
       "City": "Sao Joaquim de Bicas,",
       "StProv": "MG",
       "zip": "32920-000",
       "Country": "Brazil",
       "latitude": -20.0546,
       "longitude": -44.2749,
       "TIV": 51.4,
       "RecYear": 2015,
       "RecMonth": "05",
       "RecNumber": 1,
       "RecSubletter": "B",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-04-04T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "Sprinklers",
       "SecondaryRecType": "New Sprinklers",
       "RecKeyWords": "Automatic Sprinkler Systems Installation.",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 1340000.0,
       "LossExpectancyBefore": "1MM-5MM",
       "LossExpectancyAfterActual": 249000.0,
       "LossExpectancyAfter": "100K-500K",
       "CostToCompleteActual": 1000000.0,
       "CostToComplete": "500K-1MM",
       "ActualCostToComplete": null,
       "SavingsRatio": 1.0,
       "IntendedAction": "No Commitment",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "04 Apr 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 4,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308878,
       "RatingCatPts": "FP 0.21",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 0.76,
       "RecPriority": 2,
       "ROWNUMBER": 23,
       "SortRowNo": 23
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0008",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1588-00",
       "address": "Avenida Jorge Sachs, 650",
       "City": "Sao Joaquim de Bicas,",
       "StProv": "MG",
       "zip": "32920-000",
       "Country": "Brazil",
       "latitude": -20.0546,
       "longitude": -44.2749,
       "TIV": 51.4,
       "RecYear": 2015,
       "RecMonth": "01",
       "RecNumber": 1,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-04-04T00:00:00",
       "RecCategory": "Moderate",
       "PrimaryRecType": "Human Element",
       "SecondaryRecType": "Hot Work",
       "RecKeyWords": "Hot Work Procedure/Permit Improvements.",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 0.0,
       "LossExpectancyBefore": "HE/Reliability",
       "LossExpectancyAfterActual": 0.0,
       "LossExpectancyAfter": "Probability Reduction",
       "CostToCompleteActual": 0.0,
       "CostToComplete": "Maintenance Time",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Agree - Will Complete",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": "2019-06-30T00:00:00",
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "04 Apr 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": "30 Jun 19",
       "StatusDateMonth": 4,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": 6,
       "ExpectedCompletionDateYear": 2019,
       "RecCategoryColor": "#FFFF00",
       "ExpectedCompletionDateColor": "#FF0000",
       "UniqueID": 308866,
       "RatingCatPts": "HE 3.00",
       "RatingCatWeight": 1.60,
       "RatingScoreChange": 4.80,
       "RecPriority": 1,
       "ROWNUMBER": 24,
       "SortRowNo": 24
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0008",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1588-00",
       "address": "Avenida Jorge Sachs, 650",
       "City": "Sao Joaquim de Bicas,",
       "StProv": "MG",
       "zip": "32920-000",
       "Country": "Brazil",
       "latitude": -20.0546,
       "longitude": -44.2749,
       "TIV": 51.4,
       "RecYear": 2015,
       "RecMonth": "01",
       "RecNumber": 2,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-04-04T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "Human Element",
       "SecondaryRecType": "Elect. Maintenance",
       "RecKeyWords": "PCB-Contaminated Transformer Replacement.  ",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 0.0,
       "LossExpectancyBefore": "HE/Reliability",
       "LossExpectancyAfterActual": 0.0,
       "LossExpectancyAfter": "Probability Reduction",
       "CostToCompleteActual": 25000.0,
       "CostToComplete": "10K-25K",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Agree - Will Complete",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": "2019-12-31T00:00:00",
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "04 Apr 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": "31 Dec 19",
       "StatusDateMonth": 4,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": 12,
       "ExpectedCompletionDateYear": 2019,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308880,
       "RatingCatPts": "HE 0.30",
       "RatingCatWeight": 1.60,
       "RatingScoreChange": 0.48,
       "RecPriority": 4,
       "ROWNUMBER": 25,
       "SortRowNo": 25
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0008",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1588-00",
       "address": "Avenida Jorge Sachs, 650",
       "City": "Sao Joaquim de Bicas,",
       "StProv": "MG",
       "zip": "32920-000",
       "Country": "Brazil",
       "latitude": -20.0546,
       "longitude": -44.2749,
       "TIV": 51.4,
       "RecYear": 2015,
       "RecMonth": "01",
       "RecNumber": 3,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-04-04T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "Human Element",
       "SecondaryRecType": "Comb. Safety Testing",
       "RecKeyWords": "Painting Dryer Maintenance Improvements.  ",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 0.0,
       "LossExpectancyBefore": "HE/Reliability",
       "LossExpectancyAfterActual": 0.0,
       "LossExpectancyAfter": "Probability Reduction",
       "CostToCompleteActual": 0.0,
       "CostToComplete": "Maintenance Time",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Agree - Will Complete",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": "2019-06-30T00:00:00",
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "04 Apr 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": "30 Jun 19",
       "StatusDateMonth": 4,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": 6,
       "ExpectedCompletionDateYear": 2019,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "#FF0000",
       "UniqueID": 308874,
       "RatingCatPts": "HE 0.50",
       "RatingCatWeight": 1.60,
       "RatingScoreChange": 0.80,
       "RecPriority": 1,
       "ROWNUMBER": 26,
       "SortRowNo": 26
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0008",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1588-00",
       "address": "Avenida Jorge Sachs, 650",
       "City": "Sao Joaquim de Bicas,",
       "StProv": "MG",
       "zip": "32920-000",
       "Country": "Brazil",
       "latitude": -20.0546,
       "longitude": -44.2749,
       "TIV": 51.4,
       "RecYear": 2019,
       "RecMonth": "04",
       "RecNumber": 1,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-04-04T00:00:00",
       "RecCategory": "Moderate",
       "PrimaryRecType": "Human Element",
       "SecondaryRecType": "Mgmt. of Change",
       "RecKeyWords": "Global Risk Involvement in Plan Review Services.",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 0.0,
       "LossExpectancyBefore": "HE/Reliability",
       "LossExpectancyAfterActual": 0.0,
       "LossExpectancyAfter": "Probability Reduction",
       "CostToCompleteActual": 0.0,
       "CostToComplete": "Maintenance Time",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Will Study",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "04 Apr 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 4,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#FFFF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308868,
       "RatingCatPts": "HE 2.00",
       "RatingCatWeight": 1.60,
       "RatingScoreChange": 3.20,
       "RecPriority": 4,
       "ROWNUMBER": 27,
       "SortRowNo": 27
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0008",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1588-00",
       "address": "Avenida Jorge Sachs, 650",
       "City": "Sao Joaquim de Bicas,",
       "StProv": "MG",
       "zip": "32920-000",
       "Country": "Brazil",
       "latitude": -20.0546,
       "longitude": -44.2749,
       "TIV": 51.4,
       "RecYear": 2019,
       "RecMonth": "04",
       "RecNumber": 2,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-04-04T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "Human Element",
       "SecondaryRecType": "Impairments",
       "RecKeyWords": "Fire Protection Impairment Management Program Procedure.    ",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 0.0,
       "LossExpectancyBefore": "HE/Reliability",
       "LossExpectancyAfterActual": 0.0,
       "LossExpectancyAfter": "Probability Reduction",
       "CostToCompleteActual": 0.0,
       "CostToComplete": "Maintenance Time",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Agree - Will Complete",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "04 Apr 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 4,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308875,
       "RatingCatPts": "HE 0.50",
       "RatingCatWeight": 1.60,
       "RatingScoreChange": 0.80,
       "RecPriority": 1,
       "ROWNUMBER": 28,
       "SortRowNo": 28
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0008",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1588-00",
       "address": "Avenida Jorge Sachs, 650",
       "City": "Sao Joaquim de Bicas,",
       "StProv": "MG",
       "zip": "32920-000",
       "Country": "Brazil",
       "latitude": -20.0546,
       "longitude": -44.2749,
       "TIV": 51.4,
       "RecYear": 2019,
       "RecMonth": "04",
       "RecNumber": 3,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-04-04T00:00:00",
       "RecCategory": "Moderate",
       "PrimaryRecType": "Human Element",
       "SecondaryRecType": "Self-Inspections",
       "RecKeyWords": "Fire Protection Control Valve Inspections.  ",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 0.0,
       "LossExpectancyBefore": "HE/Reliability",
       "LossExpectancyAfterActual": 0.0,
       "LossExpectancyAfter": "Probability Reduction",
       "CostToCompleteActual": 0.0,
       "CostToComplete": "Maintenance Time",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Agree - Will Complete",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "04 Apr 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 4,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#FFFF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308869,
       "RatingCatPts": "HE 2.00",
       "RatingCatWeight": 1.60,
       "RatingScoreChange": 3.20,
       "RecPriority": 1,
       "ROWNUMBER": 29,
       "SortRowNo": 29
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0008",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1588-00",
       "address": "Avenida Jorge Sachs, 650",
       "City": "Sao Joaquim de Bicas,",
       "StProv": "MG",
       "zip": "32920-000",
       "Country": "Brazil",
       "latitude": -20.0546,
       "longitude": -44.2749,
       "TIV": 51.4,
       "RecYear": 2019,
       "RecMonth": "04",
       "RecNumber": 4,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-04-04T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "BCP",
       "SecondaryRecType": "BCP/DRP",
       "RecKeyWords": " Business Contingency Plan for Critical Equipment. ",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 0.0,
       "LossExpectancyBefore": "HE/Reliability",
       "LossExpectancyAfterActual": 0.0,
       "LossExpectancyAfter": "Probability Reduction",
       "CostToCompleteActual": 0.0,
       "CostToComplete": "Maintenance Time",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Agree - Will Complete",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "04 Apr 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 4,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308881,
       "RatingCatPts": "0.00",
       "RatingCatWeight": 1.60,
       "RatingScoreChange": 0.00,
       "RecPriority": 3,
       "ROWNUMBER": 30,
       "SortRowNo": 30
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0008",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1588-00",
       "address": "Avenida Jorge Sachs, 650",
       "City": "Sao Joaquim de Bicas,",
       "StProv": "MG",
       "zip": "32920-000",
       "Country": "Brazil",
       "latitude": -20.0546,
       "longitude": -44.2749,
       "TIV": 51.4,
       "RecYear": 2019,
       "RecMonth": "04",
       "RecNumber": 5,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-04-04T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "Spec. Hazards",
       "SecondaryRecType": "Flam Liq/Gas Handling",
       "RecKeyWords": "Secondary Containment",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 0.0,
       "LossExpectancyBefore": "HE/Reliability",
       "LossExpectancyAfterActual": 0.0,
       "LossExpectancyAfter": "Probability Reduction",
       "CostToCompleteActual": 0.0,
       "CostToComplete": "Maintenance Time",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Agree - Will Complete",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": "2019-05-01T00:00:00",
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "04 Apr 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": "01 May 19",
       "StatusDateMonth": 4,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": 5,
       "ExpectedCompletionDateYear": 2019,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "#FF0000",
       "UniqueID": 308872,
       "RatingCatPts": "FP 0.30",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 1.08,
       "RecPriority": 1,
       "ROWNUMBER": 31,
       "SortRowNo": 31
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0008",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1588-00",
       "address": "Avenida Jorge Sachs, 650",
       "City": "Sao Joaquim de Bicas,",
       "StProv": "MG",
       "zip": "32920-000",
       "Country": "Brazil",
       "latitude": -20.0546,
       "longitude": -44.2749,
       "TIV": 51.4,
       "RecYear": 2019,
       "RecMonth": "04",
       "RecNumber": 6,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-04-04T00:00:00",
       "RecCategory": "Moderate",
       "PrimaryRecType": "Surveillance",
       "SecondaryRecType": "Fire Prot. Supv.",
       "RecKeyWords": "Fire Alarm Panel Repairs",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 0.0,
       "LossExpectancyBefore": "HE/Reliability",
       "LossExpectancyAfterActual": 0.0,
       "LossExpectancyAfter": "Probability Reduction",
       "CostToCompleteActual": 0.0,
       "CostToComplete": "Maintenance Time",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Agree - Will Complete",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": "2019-05-01T00:00:00",
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "04 Apr 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": "01 May 19",
       "StatusDateMonth": 4,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": 5,
       "ExpectedCompletionDateYear": 2019,
       "RecCategoryColor": "#FFFF00",
       "ExpectedCompletionDateColor": "#FF0000",
       "UniqueID": 308867,
       "RatingCatPts": "FP 1.30",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 4.68,
       "RecPriority": 1,
       "ROWNUMBER": 32,
       "SortRowNo": 32
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0008",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1588-00",
       "address": "Avenida Jorge Sachs, 650",
       "City": "Sao Joaquim de Bicas,",
       "StProv": "MG",
       "zip": "32920-000",
       "Country": "Brazil",
       "latitude": -20.0546,
       "longitude": -44.2749,
       "TIV": 51.4,
       "RecYear": 2019,
       "RecMonth": "04",
       "RecNumber": 7,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-04-04T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "Nat. Haz/Exp.",
       "SecondaryRecType": "Other Nat. Haz/Exp.",
       "RecKeyWords": "Lightning System Maintenance",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 0.0,
       "LossExpectancyBefore": "HE/Reliability",
       "LossExpectancyAfterActual": 0.0,
       "LossExpectancyAfter": "Probability Reduction",
       "CostToCompleteActual": 0.0,
       "CostToComplete": "Maintenance Time",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Agree - Will Complete",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": "2019-05-01T00:00:00",
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "04 Apr 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": "01 May 19",
       "StatusDateMonth": 4,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": 5,
       "ExpectedCompletionDateYear": 2019,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "#FF0000",
       "UniqueID": 308879,
       "RatingCatPts": "NH 1.30",
       "RatingCatWeight": 0.50,
       "RatingScoreChange": 0.65,
       "RecPriority": 4,
       "ROWNUMBER": 33,
       "SortRowNo": 33
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0008",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1588-00",
       "address": "Avenida Jorge Sachs, 650",
       "City": "Sao Joaquim de Bicas,",
       "StProv": "MG",
       "zip": "32920-000",
       "Country": "Brazil",
       "latitude": -20.0546,
       "longitude": -44.2749,
       "TIV": 51.4,
       "RecYear": 2019,
       "RecMonth": "04",
       "RecNumber": 8,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-04-04T00:00:00",
       "RecCategory": "Low",
       "PrimaryRecType": "Spec. Hazards",
       "SecondaryRecType": "Bldg Materials",
       "RecKeyWords": "Combustible Suspended Ceilings",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 0.0,
       "LossExpectancyBefore": "HE/Reliability",
       "LossExpectancyAfterActual": 0.0,
       "LossExpectancyAfter": "Probability Reduction",
       "CostToCompleteActual": 0.0,
       "CostToComplete": "Maintenance Time",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Agree - Evaluating Options",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "04 Apr 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 4,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#00FF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308871,
       "RatingCatPts": "FP 0.75",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 2.70,
       "RecPriority": 4,
       "ROWNUMBER": 34,
       "SortRowNo": 34
   },
   {
       "Link_to_Popup": "Enter",
       "FilePrefix": "4062",
       "FileNo": "4062.0008",
       "client": "Magna International Inc.",
       "ClientLocNo": "",
       "Division": "Magna International Inc.",
       "Facility": "1588-00",
       "address": "Avenida Jorge Sachs, 650",
       "City": "Sao Joaquim de Bicas,",
       "StProv": "MG",
       "zip": "32920-000",
       "Country": "Brazil",
       "latitude": -20.0546,
       "longitude": -44.2749,
       "TIV": 51.4,
       "RecYear": 2019,
       "RecMonth": "04",
       "RecNumber": 9,
       "RecSubletter": "",
       "RecStatus": "Outstanding",
       "StatusDate": "2019-04-04T00:00:00",
       "RecCategory": "Moderate",
       "PrimaryRecType": "Manual Prot.",
       "SecondaryRecType": "Other Manual Prot.",
       "RecKeyWords": "Domestic Use of Hydrants",
       "RecCode": "",
       "Hazard": "Fire",
       "LossExpectancyBeforeActual": 0.0,
       "LossExpectancyBefore": "HE/Reliability",
       "LossExpectancyAfterActual": 0.0,
       "LossExpectancyAfter": "Probability Reduction",
       "CostToCompleteActual": 0.0,
       "CostToComplete": "Maintenance Time",
       "ActualCostToComplete": null,
       "SavingsRatio": null,
       "IntendedAction": "Agree - Evaluating Options",
       "ResponseDate": null,
       "ResponseFrom": "",
       "PlantComment": "",
       "PlantCommentLineBreak": "",
       "ExpectedCompletionDate": null,
       "MgmtRespAction": "",
       "MgmtRespDate": null,
       "MgmtRespFrom": "",
       "MgmtRespCommentLineBreak": "",
       "MgmtRespDateString": null,
       "MgmtRespComment": "",
       "CustomAccess": "Not Used",
       "PlantFeedback": "",
       "StatusDateString": "04 Apr 19",
       "ResponseDateString": null,
       "ExpectedCompletionDateString": null,
       "StatusDateMonth": 4,
       "StatusDateYear": 2019,
       "ResponseDateMonth": null,
       "ResponseDateYear": null,
       "ExpectedCompletionDateMonth": null,
       "ExpectedCompletionDateYear": null,
       "RecCategoryColor": "#FFFF00",
       "ExpectedCompletionDateColor": "Transparent",
       "UniqueID": 308865,
       "RatingCatPts": "FP 2.00",
       "RatingCatWeight": 3.60,
       "RatingScoreChange": 7.20,
       "RecPriority": 4,
       "ROWNUMBER": 35,
       "SortRowNo": 35
   }
]