'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Grids_GridMasterPage

    '''<summary>
    '''GridHeadContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridHeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''RadStyleSheetManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManager1 As Global.Telerik.Web.UI.RadStyleSheetManager

    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''RadWindow1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindow1 As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''HiddenField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenField1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HiddenPracticeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenPracticeID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents header As Global.GRC.Connect.Web.Header

    '''<summary>
    '''litSubTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSubTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Nav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nav As Global.GRC.Connect.Web.LeftNav

    '''<summary>
    '''divTopInstructions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTopInstructions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTopMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTopMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divTopInstructionsMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTopInstructionsMap As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spnInspectionProgramYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnInspectionProgramYear As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cboInspectionProgramYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboInspectionProgramYear As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divContainerMapBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContainerMapBtn As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divContainerCharts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContainerCharts As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divContainerSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContainerSearch As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''icoSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents icoSearch As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divFavoritesLibrary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFavoritesLibrary As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''icoLibrary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents icoLibrary As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divFavoritesSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFavoritesSave As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''icoFavoriteSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents icoFavoriteSave As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divExtractDownloadChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divExtractDownloadChart As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''icoChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents icoChart As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divExtractDownloadReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divExtractDownloadReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''icoReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents icoReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divExtractDownloadData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divExtractDownloadData As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''icoExtractData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents icoExtractData As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divContainerActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContainerActions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''icoResetGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents icoResetGrid As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GridBodyContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridBodyContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''HiddenContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''hidSIDParameter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidSIDParameter As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidMasterClientID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidMasterClientID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''FooterControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FooterControl As Global.GRC.Connect.Web.footer
End Class
