'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Grids_FacilityRating

    '''<summary>
    '''lblPassive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPassive As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActive As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblFlood control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFlood As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblEQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEQ As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblWindstorm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWindstorm As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblConstruction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConstruction As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblOccupancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOccupancy As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOther As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPhyProt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPhyProt As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblHE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHE As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblNatHaz control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNatHaz As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblBCP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBCP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCFlood control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCFlood As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCEQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCEQ As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCWindstorm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCWindstorm As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCConstruction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCConstruction As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCOccupancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCOccupancy As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCOther As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientFlood control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientFlood As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientEQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientEQ As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientWindstorm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientWindstorm As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientConstruction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientConstruction As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientOccupancy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientOccupancy As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientOther As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCPhyProt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCPhyProt As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCHE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCHE As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCNatHaz control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCNatHaz As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCBCP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCBCP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientPhyProt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientPhyProt As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientHE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientHE As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientNatHaz control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientNatHaz As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientBCP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientBCP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMechEquip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMechEquip As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblElecEquip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblElecEquip As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblBoilers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBoilers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblProcEquip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProcEquip As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblOccup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOccup As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCompSys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompSys As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMechMaint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMechMaint As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblElecMaint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblElecMaint As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSpares control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpares As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCMechEquip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCMechEquip As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCElecEquip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCElecEquip As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCBoilers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCBoilers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCProcEquip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCProcEquip As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCOccup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCOccup As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCCompSys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCCompSys As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientMechEquip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientMechEquip As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientElecEquip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientElecEquip As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientBoilers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientBoilers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientProcEquip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientProcEquip As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientOccup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientOccup As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientCompSys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientCompSys As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCMechMaint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCMechMaint As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCElecMaint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCElecMaint As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGRCSpares control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGRCSpares As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Label8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label8 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientMechMaint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientMechMaint As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientElecMaint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientElecMaint As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblClientSpares control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientSpares As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Label9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label9 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Label10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label10 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
