'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GRC.Connect.Libraries.PGPLib.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property BouncyCastle_CryptoExt() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BouncyCastle_CryptoExt", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property DidiSoft_Pgp() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("DidiSoft_Pgp", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property DidiSoft_Pgp_Net_LdapClient() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("DidiSoft_Pgp_Net_LdapClient", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;doc&gt;
        '''    &lt;assembly&gt;
        '''        &lt;name&gt;DidiSoft.Pgp.Net.LdapClient&lt;/name&gt;
        '''    &lt;/assembly&gt;
        '''    &lt;members&gt;
        '''        &lt;member name=&quot;T:DidiSoft.Pgp.Net.LdapClient&quot;&gt;
        '''            &lt;summary&gt;
        '''            Retrieves keys from LDAP servers that support the pgp ldap schema
        '''            &lt;/summary&gt;
        '''            &lt;example&gt;
        '''            &lt;code lang=&quot;C#&quot;&gt;
        '''            DidiSoft.Pgp.Net.LdapClient ldap = new DidiSoft.Pgp.Net.LdapClient(&quot;127.0.0.1&quot;);
        '''            byte[] keyBytes = ldap.GetKeyByUserId(&quot;Didis [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DidiSoft_Pgp_Net_LdapClient1() As String
            Get
                Return ResourceManager.GetString("DidiSoft_Pgp_Net_LdapClient1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;doc&gt;
        '''    &lt;assembly&gt;
        '''        &lt;name&gt;DidiSoft.Pgp&lt;/name&gt;
        '''    &lt;/assembly&gt;
        '''    &lt;members&gt;
        '''        &lt;member name=&quot;T:DidiSoft.Pgp.Exceptions.FileIsEncryptedException&quot;&gt;
        '''            &lt;summary&gt;
        '''            Exception that indicates that a file is encrypted.
        '''            &lt;para&gt;
        '''            This exception is thrown when we want to verify that a file was not only signed but signed and encrypted.
        '''            &lt;/para&gt;
        '''            &lt;/summary&gt;
        '''            &lt;remarks&gt;
        '''            Introduced in ver [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DidiSoft_Pgp1() As String
            Get
                Return ResourceManager.GetString("DidiSoft_Pgp1", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
