var dsNavLinkFire = [
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 2,
     "NavParentLinkId": null,
     "NavLinkId": 30,
     "NavText": "Output Reports & Charts",
     "NavUrl": null,
     "NavOrder": 1,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "FireOutputReports",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": null,
     "NavType": "Label",
     "NavComment": null,
     "NavConstant": null,
     "NavRptCode": null,
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": "15",
     "slideGroupId": "2",
     "slideLevelId": "2",
     "slideType": "all",
     "slideParentId": "5",
     "slideOrder": "4",
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 2,
     "NavParentLinkId": "30",
     "NavLinkId": 32,
     "NavText": "Inspection Details",
     "NavUrl": null,
     "NavOrder": 1,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "FireOutputReports",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": null,
     "NavType": "Label",
     "NavComment": null,
     "NavConstant": null,
     "NavRptCode": null,
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": "17",
     "slideGroupId": "3",
     "slideLevelId": "3",
     "slideType": "all",
     "slideParentId": "15",
     "slideOrder": "1",
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 2,
     "NavParentLinkId": "30",
     "NavLinkId": 33,
     "NavText": "Ratings",
     "NavUrl": null,
     "NavOrder": 2,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "FireOutputReports",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": null,
     "NavType": "Label",
     "NavComment": null,
     "NavConstant": null,
     "NavRptCode": null,
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": "18",
     "slideGroupId": "3",
     "slideLevelId": "3",
     "slideType": "all",
     "slideParentId": "15",
     "slideOrder": "2",
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 2,
     "NavParentLinkId": "30",
     "NavLinkId": 34,
     "NavText": "C.O.P.E",
     "NavUrl": null,
     "NavOrder": 3,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "FireOutputReports",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": null,
     "NavType": "Label",
     "NavComment": null,
     "NavConstant": null,
     "NavRptCode": null,
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": "19",
     "slideGroupId": "3",
     "slideLevelId": "3",
     "slideType": "all",
     "slideParentId": "15",
     "slideOrder": "3",
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 2,
     "NavParentLinkId": "30",
     "NavLinkId": 35,
     "NavText": "Active Recommendations",
     "NavUrl": null,
     "NavOrder": 4,
     "NavToolTip": "Excludes CONFIRMED COMPLETED & REMOVED Statuses",
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "FireOutputReports",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": null,
     "NavType": "Label",
     "NavComment": null,
     "NavConstant": null,
     "NavRptCode": null,
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": "20",
     "slideGroupId": "3",
     "slideLevelId": "3",
     "slideType": "all",
     "slideParentId": "15",
     "slideOrder": "4",
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 2,
     "NavParentLinkId": "30",
     "NavLinkId": 36,
     "NavText": "All Recommendations",
     "NavUrl": null,
     "NavOrder": 5,
     "NavToolTip": "Includes ALL Statuses",
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "FireOutputReports",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": null,
     "NavType": "Label",
     "NavComment": null,
     "NavConstant": 3,
     "NavRptCode": null,
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": "21",
     "slideGroupId": "3",
     "slideLevelId": "3",
     "slideType": "all",
     "slideParentId": "15",
     "slideOrder": "5",
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 2,
     "NavParentLinkId": "30",
     "NavLinkId": 37,
     "NavText": "Loss Estimates",
     "NavUrl": null,
     "NavOrder": 6,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "FireOutputReports",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": null,
     "NavType": "Label",
     "NavComment": null,
     "NavConstant": null,
     "NavRptCode": null,
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": "22",
     "slideGroupId": "3",
     "slideLevelId": "3",
     "slideType": "all",
     "slideParentId": "15",
     "slideOrder": "6",
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 2,
     "NavParentLinkId": "30",
     "NavLinkId": 60,
     "NavText": "Impairments",
     "NavUrl": null,
     "NavOrder": 7,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "FireOutputReports",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": null,
     "NavType": "Label",
     "NavComment": null,
     "NavConstant": null,
     "NavRptCode": null,
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": "23",
     "slideGroupId": "3",
     "slideLevelId": "3",
     "slideType": "all",
     "slideParentId": "15",
     "slideOrder": "7",
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 4,
     "NavParentLinkId": "32",
     "NavLinkId": 511,
     "NavText": "Inspection Frequency",
     "NavUrl": null,
     "NavOrder": 2,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": null,
     "NavType": "BatchReports",
     "NavComment": "21104 ",
     "NavConstant": null,
     "NavRptCode": "110",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 4,
     "NavParentLinkId": "32",
     "NavLinkId": 512,
     "NavText": "Inspection Status",
     "NavUrl": null,
     "NavOrder": 3,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": null,
     "NavType": "BatchReports",
     "NavComment": "21100 ",
     "NavConstant": null,
     "NavRptCode": "106",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 4,
     "NavParentLinkId": "33",
     "NavLinkId": 513,
     "NavText": "Total Facility Score Chart",
     "NavUrl": "_BASE1_/Charts/Default.aspx?targetFolderName=FacilityScore&targetPageName=FacilityScore&Division=All&CustomAccess=All&Currency=US%20Dollar&TIV=All&InspectionProgramYear=&Page=1",
     "NavOrder": 4,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchCharts",
     "NavComment": "RptCode=19, 11200 ",
     "NavConstant": null,
     "NavRptCode": "227",
     "NavGridId": null,
     "NavChartId": "4",
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 4,
     "NavParentLinkId": "33",
     "NavLinkId": 514,
     "NavText": "Rating Summary",
     "NavUrl": null,
     "NavOrder": 5,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "11106 ",
     "NavConstant": null,
     "NavRptCode": "7",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 4,
     "NavParentLinkId": "33",
     "NavLinkId": 515,
     "NavText": "Rating Detail",
     "NavUrl": null,
     "NavOrder": 6,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "11112 ",
     "NavConstant": null,
     "NavRptCode": "13",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 4,
     "NavParentLinkId": "34",
     "NavLinkId": 516,
     "NavText": "C.O.P.E Report (All Locations)",
     "NavUrl": null,
     "NavOrder": 9,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "21109 ",
     "NavConstant": null,
     "NavRptCode": "115",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 4,
     "NavParentLinkId": "34",
     "NavLinkId": 517,
     "NavText": "C.O.P.E Summary",
     "NavUrl": null,
     "NavOrder": 10,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "11115 ",
     "NavConstant": null,
     "NavRptCode": "16",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 4,
     "NavParentLinkId": "34",
     "NavLinkId": 518,
     "NavText": "Human Element Summary",
     "NavUrl": null,
     "NavOrder": 11,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "11108 ",
     "NavConstant": null,
     "NavRptCode": "9",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 4,
     "NavParentLinkId": "36",
     "NavLinkId": 519,
     "NavText": "All Recs By Type",
     "NavUrl": null,
     "NavOrder": 12,
     "NavToolTip": null,
     "NavVisible": 0,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "11103 ",
     "NavConstant": null,
     "NavRptCode": "4",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 4,
     "NavParentLinkId": "35",
     "NavLinkId": 521,
     "NavText": "Active Recs By Impact",
     "NavUrl": "_BASE1_/Charts/Default.aspx?RecStatus=Active",
     "NavOrder": 14,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchCharts",
     "NavComment": "RptCode=21, 11202 ",
     "NavConstant": null,
     "NavRptCode": "214",
     "NavGridId": null,
     "NavChartId": "42",
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 4,
     "NavParentLinkId": "35",
     "NavLinkId": 522,
     "NavText": "Active Recs By Loss Estimates",
     "NavUrl": "_BASE1_/Charts/Default.aspx?RecStatus=Active",
     "NavOrder": 15,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchCharts",
     "NavComment": "RptCode=22, 11203 ",
     "NavConstant": null,
     "NavRptCode": "230",
     "NavGridId": null,
     "NavChartId": "56",
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 4,
     "NavParentLinkId": "35",
     "NavLinkId": 523,
     "NavText": "Pending Rec Resp & Follow-Up",
     "NavUrl": null,
     "NavOrder": 16,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "11101 ",
     "NavConstant": null,
     "NavRptCode": "2",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 4,
     "NavParentLinkId": "35",
     "NavLinkId": 524,
     "NavText": "Pending Rec Resp & Tracking",
     "NavUrl": null,
     "NavOrder": 17,
     "NavToolTip": null,
     "NavVisible": 0,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "11102 ",
     "NavConstant": null,
     "NavRptCode": "3",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 4,
     "NavParentLinkId": "36",
     "NavLinkId": 526,
     "NavText": "All Recs By Status",
     "NavUrl": "_BASE1_/Charts/Default.aspx?DrillLevel=0&PrimaryRecType=All",
     "NavOrder": 19,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchCharts",
     "NavComment": "RptCode=23, 11204 ",
     "NavConstant": null,
     "NavRptCode": "220",
     "NavGridId": null,
     "NavChartId": "48",
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 4,
     "NavParentLinkId": "36",
     "NavLinkId": 527,
     "NavText": "All Rec Resp Follow-Up",
     "NavUrl": null,
     "NavOrder": 20,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "11104 ",
     "NavConstant": null,
     "NavRptCode": "5",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 4,
     "NavParentLinkId": "36",
     "NavLinkId": 528,
     "NavText": "All Rec Resp Tracking",
     "NavUrl": null,
     "NavOrder": 21,
     "NavToolTip": null,
     "NavVisible": 0,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "11105 ",
     "NavConstant": null,
     "NavRptCode": "6",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 4,
     "NavParentLinkId": "37",
     "NavLinkId": 529,
     "NavText": "Location Loss Estimates",
     "NavUrl": null,
     "NavOrder": 22,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "11109 ",
     "NavConstant": null,
     "NavRptCode": "10",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 4,
     "NavParentLinkId": "35",
     "NavLinkId": 530,
     "NavText": "Active Recs By Type",
     "NavUrl": null,
     "NavOrder": 12,
     "NavToolTip": null,
     "NavVisible": 0,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "11100 ",
     "NavConstant": null,
     "NavRptCode": "1",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 4,
     "NavParentLinkId": "35",
     "NavLinkId": 531,
     "NavText": "Active Recs By Type Chart (Prim. & Sec.)",
     "NavUrl": "_BASE1_/Charts/Default.aspx?DrillLevel=0&PrimaryRecType=All",
     "NavOrder": 13,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchCharts",
     "NavComment": "RptCode=20, 11201 ",
     "NavConstant": null,
     "NavRptCode": "174",
     "NavGridId": null,
     "NavChartId": "1",
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 2,
     "NavParentLinkId": "60",
     "NavLinkId": 547,
     "NavText": "Impairment Details",
     "NavUrl": null,
     "NavOrder": 1,
     "NavToolTip": null,
     "NavVisible": 0,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "21101 Review",
     "NavConstant": null,
     "NavRptCode": "21101",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 2,
     "NavParentLinkId": "60",
     "NavLinkId": 621,
     "NavText": "Impairment Summary",
     "NavUrl": null,
     "NavOrder": 1,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "21111 Review",
     "NavConstant": null,
     "NavRptCode": "117",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 2,
     "NavParentLinkId": "60",
     "NavLinkId": 622,
     "NavText": "Impairment Summary Chart",
     "NavUrl": null,
     "NavOrder": 1,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "RptCode=118, 21112 Review",
     "NavConstant": null,
     "NavRptCode": "118",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 2,
     "NavParentLinkId": "35",
     "NavLinkId": 644,
     "NavText": "Active Recs By Intended Action",
     "NavUrl": "_BASE1_/Charts/Default.aspx?DrillLevel=0&PrimaryRecType=All",
     "NavOrder": 15,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchCharts",
     "NavComment": null,
     "NavConstant": null,
     "NavRptCode": "234",
     "NavGridId": null,
     "NavChartId": "69",
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 9,
     "NavLevelId": 2,
     "NavParentLinkId": "36",
     "NavLinkId": 645,
     "NavText": "All Recs By Intended Action",
     "NavUrl": "_BASE1_/Charts/Default.aspx?DrillLevel=0&PrimaryRecType=All",
     "NavOrder": 20,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "FireBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchCharts",
     "NavComment": null,
     "NavConstant": null,
     "NavRptCode": "235",
     "NavGridId": null,
     "NavChartId": "70",
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 }
];





var dsNavLinksBoiler = [
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": null,
     "NavLinkId": 94,
     "NavText": "Output Reports & Charts",
     "NavUrl": null,
     "NavOrder": 1,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "BMOutputReports",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": null,
     "NavType": "Label",
     "NavComment": null,
     "NavConstant": null,
     "NavRptCode": null,
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": "65",
     "slideGroupId": "13",
     "slideLevelId": "2",
     "slideType": "all",
     "slideParentId": "6",
     "slideOrder": "4",
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "94",
     "NavLinkId": 96,
     "NavText": "Inspection Details",
     "NavUrl": null,
     "NavOrder": 1,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "BMOutputReports",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": null,
     "NavType": "Label",
     "NavComment": null,
     "NavConstant": null,
     "NavRptCode": null,
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": "70",
     "slideGroupId": "14",
     "slideLevelId": "3",
     "slideType": "all",
     "slideParentId": "65",
     "slideOrder": "1",
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "94",
     "NavLinkId": 97,
     "NavText": "Ratings",
     "NavUrl": null,
     "NavOrder": 2,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "BMOutputReports",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "",
     "NavType": "Label",
     "NavComment": null,
     "NavConstant": null,
     "NavRptCode": null,
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": "71",
     "slideGroupId": "14",
     "slideLevelId": "3",
     "slideType": "all",
     "slideParentId": "65",
     "slideOrder": "2",
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "94",
     "NavLinkId": 98,
     "NavText": "Facility Data",
     "NavUrl": null,
     "NavOrder": 3,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "BMOutputReports",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "",
     "NavType": "Label",
     "NavComment": null,
     "NavConstant": null,
     "NavRptCode": null,
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": "72",
     "slideGroupId": "14",
     "slideLevelId": "3",
     "slideType": "all",
     "slideParentId": "65",
     "slideOrder": "3",
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "94",
     "NavLinkId": 99,
     "NavText": "Active Recommendations",
     "NavUrl": null,
     "NavOrder": 4,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "BMOutputReports",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "",
     "NavType": "Label",
     "NavComment": null,
     "NavConstant": null,
     "NavRptCode": null,
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": "73",
     "slideGroupId": "14",
     "slideLevelId": "3",
     "slideType": "all",
     "slideParentId": "65",
     "slideOrder": "4",
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "94",
     "NavLinkId": 100,
     "NavText": "All Recommendations",
     "NavUrl": null,
     "NavOrder": 5,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "BMOutputReports",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "",
     "NavType": "Label",
     "NavComment": null,
     "NavConstant": 4,
     "NavRptCode": null,
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": "74",
     "slideGroupId": "14",
     "slideLevelId": "3",
     "slideType": "all",
     "slideParentId": "65",
     "slideOrder": "5",
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "94",
     "NavLinkId": 392,
     "NavText": "Loss Estimates",
     "NavUrl": null,
     "NavOrder": 6,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "BMOutputReports",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "",
     "NavType": "Label",
     "NavComment": null,
     "NavConstant": null,
     "NavRptCode": null,
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": "75",
     "slideGroupId": "14",
     "slideLevelId": "3",
     "slideType": "all",
     "slideParentId": "65",
     "slideOrder": "6",
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "96",
     "NavLinkId": 536,
     "NavText": "Inspection Status",
     "NavUrl": null,
     "NavOrder": 3,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": null,
     "NavType": "BatchReports",
     "NavComment": "22100 ",
     "NavConstant": null,
     "NavRptCode": "121",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "96",
     "NavLinkId": 537,
     "NavText": "Inspection Frequency",
     "NavUrl": null,
     "NavOrder": 2,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": null,
     "NavType": "BatchReports",
     "NavComment": "22104 ",
     "NavConstant": 8,
     "NavRptCode": "124",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "97",
     "NavLinkId": 538,
     "NavText": "Total Facility Score Chart",
     "NavUrl": "_BASE1_/Charts/Default.aspx?targetFolderName=FacilityScore&targetPageName=FacilityScore&Division=All&CustomAccess=All&Currency=US%20Dollar&TIV=All&InspectionProgramYear=&Page=1",
     "NavOrder": 1,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchCharts",
     "NavComment": "RptCode=40, 12200 ",
     "NavConstant": null,
     "NavRptCode": "228",
     "NavGridId": null,
     "NavChartId": "54",
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "97",
     "NavLinkId": 539,
     "NavText": "Rating Summary Report",
     "NavUrl": null,
     "NavOrder": 2,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "12112 ",
     "NavConstant": null,
     "NavRptCode": "37",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "97",
     "NavLinkId": 540,
     "NavText": "Rating Detail Report",
     "NavUrl": null,
     "NavOrder": 3,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "12110 ",
     "NavConstant": null,
     "NavRptCode": "35",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "98",
     "NavLinkId": 541,
     "NavText": "Facility Data Report (All Locations)",
     "NavUrl": null,
     "NavOrder": 1,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "22110 ",
     "NavConstant": 1,
     "NavRptCode": "130",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "98",
     "NavLinkId": 543,
     "NavText": "Mech. Maint. Summary",
     "NavUrl": null,
     "NavOrder": 3,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "12109 ",
     "NavConstant": 28,
     "NavRptCode": "34",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "98",
     "NavLinkId": 544,
     "NavText": "Elect. Maint. Summary",
     "NavUrl": null,
     "NavOrder": 4,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "12100 ",
     "NavConstant": 0,
     "NavRptCode": "25",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "98",
     "NavLinkId": 545,
     "NavText": "Human Element Summary",
     "NavUrl": null,
     "NavOrder": 4,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "12111 ",
     "NavConstant": 0,
     "NavRptCode": "36",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "98",
     "NavLinkId": 546,
     "NavText": "Facility Data Summary",
     "NavUrl": null,
     "NavOrder": 2,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "12101 ",
     "NavConstant": 27,
     "NavRptCode": "26",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "99",
     "NavLinkId": 548,
     "NavText": "Active Recs By Type",
     "NavUrl": null,
     "NavOrder": 1,
     "NavToolTip": null,
     "NavVisible": 0,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "12103 ",
     "NavConstant": 15,
     "NavRptCode": "28",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "99",
     "NavLinkId": 549,
     "NavText": "Active Recs By Type Chart (Prim. & Sec.)",
     "NavUrl": "_BASE1_/Charts/Default.aspx?DrillLevel=0&PrimaryRecType=All&RecStatus=Active",
     "NavOrder": 2,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchCharts",
     "NavComment": "RptCode=43, 12203 ",
     "NavConstant": 16,
     "NavRptCode": "179",
     "NavGridId": null,
     "NavChartId": "31",
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "99",
     "NavLinkId": 550,
     "NavText": "Active Recs By Impact",
     "NavUrl": "_BASE1_/Charts/Default.aspx?RecStatus=Active",
     "NavOrder": 3,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchCharts",
     "NavComment": "12204 ",
     "NavConstant": 17,
     "NavRptCode": "215",
     "NavGridId": null,
     "NavChartId": "43",
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "99",
     "NavLinkId": 551,
     "NavText": "Active Recs By Loss Estimates",
     "NavUrl": "_BASE1_/Charts/Default.aspx?RecStatus=Active",
     "NavOrder": 4,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchCharts",
     "NavComment": "12205 ",
     "NavConstant": 18,
     "NavRptCode": "229",
     "NavGridId": null,
     "NavChartId": "55",
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "99",
     "NavLinkId": 552,
     "NavText": "Pending Rec Resp & Follow-Up",
     "NavUrl": null,
     "NavOrder": 5,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "12104 ",
     "NavConstant": 19,
     "NavRptCode": "29",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "99",
     "NavLinkId": 553,
     "NavText": "Pending Rec Resp & Tracking",
     "NavUrl": null,
     "NavOrder": 6,
     "NavToolTip": null,
     "NavVisible": 0,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "12105 ",
     "NavConstant": 20,
     "NavRptCode": "30",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "100",
     "NavLinkId": 554,
     "NavText": "All Recs By Type",
     "NavUrl": null,
     "NavOrder": 1,
     "NavToolTip": null,
     "NavVisible": 0,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "12106 ",
     "NavConstant": 22,
     "NavRptCode": "31",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "100",
     "NavLinkId": 555,
     "NavText": "All Recs By Status",
     "NavUrl": "_BASE1_/Charts/Default.aspx?DrillLevel=0&PrimaryRecType=All",
     "NavOrder": 2,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchCharts",
     "NavComment": "12206 ",
     "NavConstant": 21,
     "NavRptCode": "226",
     "NavGridId": null,
     "NavChartId": "49",
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "100",
     "NavLinkId": 556,
     "NavText": "All Rec Resp Follow-Up",
     "NavUrl": null,
     "NavOrder": 3,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "12107 ",
     "NavConstant": 23,
     "NavRptCode": "32",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "100",
     "NavLinkId": 557,
     "NavText": "All Rec Resp Tracking",
     "NavUrl": null,
     "NavOrder": 4,
     "NavToolTip": null,
     "NavVisible": 0,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchReports",
     "NavComment": "12108 ",
     "NavConstant": 24,
     "NavRptCode": "33",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "392",
     "NavLinkId": 558,
     "NavText": "Location Loss Estimates",
     "NavUrl": null,
     "NavOrder": 1,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": null,
     "NavType": "BatchReports",
     "NavComment": "22109 Review",
     "NavConstant": 31,
     "NavRptCode": "129",
     "NavGridId": null,
     "NavChartId": null,
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "99",
     "NavLinkId": 646,
     "NavText": "Active Recs By Intended Action",
     "NavUrl": "_BASE1_/Charts/Default.aspx?DrillLevel=0&PrimaryRecType=All",
     "NavOrder": 4,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchCharts",
     "NavComment": null,
     "NavConstant": null,
     "NavRptCode": "236",
     "NavGridId": null,
     "NavChartId": "67",
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 },
 {
     "NavControlId": 1,
     "NavPracticeID": 10,
     "NavLevelId": 2,
     "NavParentLinkId": "100",
     "NavLinkId": 647,
     "NavText": "All Recs By Intended Action",
     "NavUrl": "_BASE1_/Charts/Default.aspx?DrillLevel=0&PrimaryRecType=All",
     "NavOrder": 3,
     "NavToolTip": null,
     "NavVisible": 1,
     "NavEnabled": 1,
     "NavSpcFeature": "",
     "NavIsPracticeTopLink": 0,
     "NavDefaultExpanded": 0,
     "NavSiteMapKeyword": "",
     "NavAllReportsKeyword": "BMBatchReports",
     "NavAllDataKeyword": null,
     "NavTarget": "_blank",
     "NavType": "BatchCharts",
     "NavComment": null,
     "NavConstant": null,
     "NavRptCode": "237",
     "NavGridId": null,
     "NavChartId": "68",
     "NavExtractId": null,
     "NavBypassFilter": 0,
     "NavStatusToolTip": null,
     "slideMenuId": null,
     "slideGroupId": null,
     "slideLevelId": null,
     "slideType": null,
     "slideParentId": null,
     "slideOrder": null,
     "slideImageClassName": null,
     "IsClientAdmin": 0
 }
];





var dsBatchReports = {
    "isSuccess": true,
    "message": null,
    "data": [
        {
            "practiceCode": 520,
            "iconName": "icon-fire-prevention.png",
            "practiceNameText": "Fire Protection Engineering",
            "practiceNameSubText": "Output Reports & Charts",
            "navLinks": dsNavLinkFire
        },
        {
            "practiceCode": 510,
            "iconName": "icon-boiler-machinery.png",
            "practiceNameText": "Boiler & Machinery Engineering",
            "practiceNameSubText": "Output Reports & Charts",
            "navLinks": dsNavLinksBoiler
        }
    ]
};



