'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProgramStatus_Form_Server

    '''<summary>
    '''lblCompanyNameForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyNameForm As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrintCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrintCompanyName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrencySetting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrencySetting As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divAverageGRCFacilityScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAverageGRCFacilityScore As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divChartFireRating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divChartFireRating As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divChartBMRating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divChartBMRating As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divAverageIndustryGroupFacilityScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAverageIndustryGroupFacilityScore As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divNoLocationsWithBottom5LowestRatings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNoLocationsWithBottom5LowestRatings As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spnFireNoRatingsChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnFireNoRatingsChart As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spnBMNoRatingsChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnBMNoRatingsChart As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divCustomFeaturePlaceholder1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCustomFeaturePlaceholder1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divCustomFeaturePlaceholder2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCustomFeaturePlaceholder2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divCustomFeaturePlaceholder3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCustomFeaturePlaceholder3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divJurisObjectsOverdue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divJurisObjectsOverdue As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
