'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Charts_AutoRecommendationResponseFollowUpStatus

    '''<summary>
    '''lblDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDivision As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDivisionValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDivisionValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCustomAccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomAccess As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCustomAccessValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomAccessValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDateRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateRange As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDateRangeValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateRangeValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOverall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOverall As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPractice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPractice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFire As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNatHaz control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNatHaz As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInfrared control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfrared As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoOfRequestsSent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoOfRequestsSent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPercentResponsesCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPercentResponsesCompleted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPercentResponsesOutstanding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPercentResponsesOutstanding As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAllCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllCompleted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLocsWithAllResponsesCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocsWithAllResponsesCompleted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPartialCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPartialCompleted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLocsWithPartialResponsesCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocsWithPartialResponsesCompleted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFollowUpStagePartialResponsesCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFollowUpStagePartialResponsesCompleted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInitialRequestPartialResponsesCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInitialRequestPartialResponsesCompleted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFirstFollowUpPartialResponsesCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstFollowUpPartialResponsesCompleted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSecondFollowUpPartialResponsesCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSecondFollowUpPartialResponsesCompleted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblThirdFollowUpPartialResponsesCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblThirdFollowUpPartialResponsesCompleted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNoneCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoneCompleted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLocsWithNoResponsesCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocsWithNoResponsesCompleted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFollowUpStageNoResponsesCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFollowUpStageNoResponsesCompleted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInitialRequestNoResponsesCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInitialRequestNoResponsesCompleted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFirstFollowUpNoResponsesCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstFollowUpNoResponsesCompleted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSecondFollowUpNoResponsesCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSecondFollowUpNoResponsesCompleted As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblThirdFollowUpNoResponsesCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblThirdFollowUpNoResponsesCompleted As Global.System.Web.UI.WebControls.Label
End Class
