Namespace razor
    Partial Public Class TblMetaReport
        Public Enum Reports
            FireActiveRecommendationsByTypeReport = 1
            FirePendingRecommendationResponsesFollowUpReport = 2
            FirePendingRecommendationResponsesTrackingReport = 3
            FireAllRecommendationsByTypeReport = 4
            FireAllRecommendationResponsesFollowUpReport = 5
            FireAllRecommendationResponsesTrackingReport = 6
            FireFacilityRatingSummaryReport = 7
            FireRecommendationsReport = 8
            FireHumanElementSummaryReport = 9
            FireLossEstimatesByLocationReport = 10
            FireCleaningElectricalSummaryReport = 11
            FireExtinguishersHazardControlsSummaryReport = 12
            FireFacilityRatingDetailReport = 13
            FireMiscellaneousSummaryReport = 14
            FireSprinklerSystemSummaryReport = 15
            FireCopeSummaryReport = 16
            FirePendingRecommendationResponsesFollowUpAutoRequestReport1st = 17
            FirePendingRecommendationResponsesTrackingExpectedOverdueReport = 18
            FireBenchmarkActivePassiveChart = 19
            FireActiveRecommendationsByTypeChart = 20
            FireActiveRecommendationsByImpactChart = 21
            FireActiveRecommendationsByLossEstimatesChart = 22
            FireAllRecommendationsByStatusChart = 23
            FireAllRecommendationsByTypeChart = 24
            BMElectMaintenanceSummaryReport = 25
            BMFacilityDataSummaryReport = 26
            BMRecommendationsReport = 27
            BMActiveRecommendationsByTypeReport = 28
            BMPendingRecommendationResponsesFollowUpReport = 29
            BMPendingRecommendationResponsesTrackingReport = 30
            BMAllRecommendationsByTypeReport = 31
            BMAllRecommendationResponsesFollowUpReport = 32
            BMAllRecommendationResponsesTrackingReport = 33
            BMMechMaintenanceSummaryReport = 34
            BMFacilityRatingDetailReport = 35
            BMHumanElementSummaryReport = 36
            BMFacilityRatingSummaryReport = 37
            BMPendingRecommendationResponsesFollowUpAutoRequestReport1st = 38
            BMPendingRecommendationResponsesTrackingExpectedOverdueReport = 39
            BMBenchmarkActivePassiveChart = 40
            BMTrendByLocationChart = 41
            BMTrendByTIVChart = 42
            BMActiveRecommendationsByTypeChart = 43
            BMActiveRecommendationsByImpactChart = 44
            BMActiveRecommendationsByLossEstimatesChart = 45
            BMAllRecommendationsByStatusChart = 46
            BMAllRecommendationsByTypeChart = 47
            IRActiveRecommendationsByTypeReport = 49
            IRPendingRecommendationResponsesFollowUpReport = 50
            IRPendingRecommendationResponsesTrackingReport = 51
            IRAllRecommendationsByTypeReport = 52
            IRAllRecommendationResponsesFollowUpReport = 53
            IRAllRecommendationResponsesTrackingReport = 54
            IRPendingRecommendationResponsesFollowUpAutoRequestReport1st = 55
            IRPendingRecommendationResponsesTrackingExpectedOverdueReport = 56
            IRActiveRecommendationsByTypeChart = 57
            IRActiveRecommendationsByImpactChart = 58
            IRAllRecommendationsByStatusChart = 59
            IRAllRecommendationsByTypeChart = 60
            FloodActiveRecommendationsByTypeReport = 61
            FloodPendingRecommendationResponsesFollowUpReport = 62
            FloodPendingRecommendationResponsesTrackingReport = 63
            FloodAllRecommendationsByTypeReport = 64
            FloodAllRecommendationResponsesFollowUpReport = 65
            FloodAllRecommendationResponsesTrackingReport = 66
            FloodFloodAssessmentGeneralReport = 67
            FloodFloodAssessmentExpBldgStructOtherReport = 68
            FloodPendingRecommendationResponsesFollowUpAutoRequestReport1st = 69
            FloodPendingRecommendationResponsesTrackingExpectedOverdueReport = 70
            FloodActiveRecommendationsByTypeChart = 71
            FloodActiveRecommendationsByImpactChart = 72
            FloodActiveRecommendationsByLossEstimatesChart = 73
            FloodAllRecommendationsByStatusChart = 74
            FloodAllRecommendationsByTypeChart = 75
            SeismicActiveRecommendationsByTypeReport = 76
            SeismicPendingRecommendationResponsesFollowUpReport = 77
            SeismicPendingRecommendationResponsesTrackingReport = 78
            SeismicAllRecommendationsByTypeReport = 79
            SeismicAllRecommendationResponsesFollowUpReport = 80
            SeismicAllRecommendationResponsesTrackingReport = 81
            SeismicSeismicStructuralReport = 82
            SeismicSeismicNonstructuralReport = 83
            SeismicPendingRecommendationResponsesFollowUpAutoRequestReport1st = 84
            SeismicPendingRecommendationResponsesTrackingExpectedOverdueReport = 85
            SeismicActiveRecommendationsByTypeChart = 86
            SeismicActiveRecommendationsByImpactChart = 87
            SeismicActiveRecommendationsByLossEstimatesChart = 88
            SeismicAllRecommendationsByStatusChart = 89
            SeismicAllRecommendationsByTypeChart = 90
            WindWindUtilitiesMiscellaneousOtherReport = 91
            WindWindBuildingEnvelopeReport = 92
            WindAllRecommendationResponsesTrackingReport = 93
            WindAllRecommendationResponsesFollowUpReport = 94
            WindAllRecommendationsByTypeReport = 95
            WindPendingRecommendationResponsesTrackingReport = 96
            WindPendingRecommendationResponsesFollowUpReport = 97
            WindActiveRecommendationsByTypeReport = 98
            WindPendingRecommendationResponsesFollowUpAutoRequestReport1st = 99
            WindPendingRecommendationResponsesTrackingExpectedOverdueReport = 100
            WindAllRecommendationsByStatusChart = 101
            WindActiveRecommendationsByImpactChart = 102
            WindActiveRecommendationsByTypeChart = 103
            WindActiveRecommendationsByLossEstimatesChart = 104
            WindAllRecommendationsByTypeChart = 105
            FireInspectionStatusReport = 106
            FirePlanReviewReport = 108
            FireRecommendationResponseReport = 109
            FireInspectionFrequencyReport = 110
            FireCopeDataSummaryReport = 111
            FireCopeDataSummaryRatingReport = 112
            FireCopeDataReport = 113
            FireFacilityRatingReport = 114
            FireAllCopeDataReport = 115
            FireImpairmentSummaryReport = 117
            FireImpairmentOverviewReport = 118
            FireRiskImprovementChart = 120
            BMInspectionStatusReport = 121
            BMPlanReviewReport = 122
            BMRecommendationResponseReport = 123
            BMInspectionFrequencyReport = 124
            BMFacilityDataSummaryLocationReport = 125
            BMFacilityDataSummaryRatingLocationReport = 126
            BMFacilityDataReport = 127
            BMFacilityRatingReport = 128
            BMLossEstimatesLocationReport = 129
            BMAllFacilityDataReport = 130
            BMRiskImprovementChart = 132
            JurisViolationReport = 134
            JurisObjectsReport = 136
            IRInspectionStatusReport = 137
            IRRecommendationResponseReport = 138
            IRInspectionFrequencyReport = 139
            IREquipmentListingReport = 140
            FloodInspectionStatusReport = 142
            FloodInspectionFrequencyReport = 143
            FloodRecommendationResponseReport = 144
            SeismicInspectionStatusReport = 146
            SeismicInspectionFrequencyReport = 147
            SeismicRecommendationResponseReport = 148
            WindInspectionStatusReport = 150
            WindInspectionFrequencyReport = 151
            WindRecommendationResponseReport = 152
            QualityOfRiskScoreCardReport = 154
            ProgramStatusReport = 155
            QualityOfRiskChart = 156
            FireBMFacilityRatingSummaryReport = 160
            FireLossPreventionRecommendationsChart = 174
            NatHazWindLossPreventionRecommendationsChart = 175
            NatHazFloodLossPreventionRecommendationsChart = 176
            NatHazSeismicLossPreventionRecommendationsChart = 177
            IRLossPreventionRecommendationsChart = 178
            BMLossPreventionRecommendationsChart = 179
            FireLossPreventionRecommendationsBCPChart = 180
            FireLossPreventionRecommendationsHumanElementChart = 181
            FireLossPreventionRecommendationsManualProtChart = 182
            FireLossPreventionRecommendationsNatHazExpChart = 183
            FireLossPreventionRecommendationsSpecHazardsChart = 184
            FireLossPreventionRecommendationsSprinklersChart = 185
            FireLossPreventionRecommendationsSurveillanceChart = 186
            FireLossPreventionRecommendationsWaterSupplyChart = 187
            NatHazWindLossPreventionRecommendationsRoofChart = 188
            NatHazWindLossPreventionRecommendationsWallsChart = 189
            NatHazWindLossPreventionRecommendationsUtilitiesChart = 190
            NatHazWindLossPreventionRecommendationsMiscChart = 191
            NatHazFloodLossPreventionRecommendationsBldgChart = 192
            NatHazFloodLossPreventionRecommendationsExposureChart = 193
            NatHazFloodLossPreventionRecommendationsOtherChart = 194
            NatHazSeismicLossPreventionRecommendationsStrucChart = 195
            NatHazSeismicLossPreventionRecommendationsNonStrucChart = 196
            IRLossPreventionRecommendationsUnclassifiedChart = 197
            IRLossPreventionRecommendationsFireChart = 198
            IRLossPreventionRecommendationsBoilerChart = 199
            IRLossPreventionRecommendationsMechanicalChart = 200
            IRLossPreventionRecommendationsEngMaintChart = 201
            IRLossPreventionRecommendationsArcFlashChart = 202
            IRLossPreventionRecommendationsElectricalChart = 203
            BMLossPreventionRecommendationsBCPChart = 204
            BMLossPreventionRecommendationsBoilPresVessTankChart = 205
            BMLossPreventionRecommendationsCompSysChart = 206
            BMLossPreventionRecommendationsCriticalSparesChart = 207
            BMLossPreventionRecommendationsElecPrevPredMaintChart = 208
            BMLossPreventionRecommendationsElecSysChart = 209
            BMLossPreventionRecommendationsHumanElementChart = 210
            BMLossPreventionRecommendationsMechPrevPredMaintChart = 211
            BMLossPreventionRecommendationsMechSysChart = 212
            BMLossPreventionRecommendationsProdProcessEquipChart = 213
            FireRecommendationsByImpactChart = 214
            BMRecommendationsByImpactChart = 215
            IRRecommendationsByImpactChart = 216
            NatHazSeismicRecommendationsByImpactChart = 217
            NatHazFloodRecommendationsByImpactChart = 218
            NatHazWindRecommendationsByImpactChart = 219
            FireRecommendationsByStatusChart = 220
            BMRecommendationsByStatusChart = 221
            IRRecommendationsByStatusChart = 222
            NatHazSeismicRecommendationsByStatusChart = 224
            NatHazFloodRecommendationsByStatusChart = 225
            NatHazWindRecommendationsByStatusChart = 226
            FireBenchmarkRatingTotalFacilityScoreChart = 227
            BoilerBenchmarkRatingTotalFacilityScoreChart = 228
            BMRecommendationsByLERangeChart = 229
            FireRecommendationsByLERangeChart = 230
            RecFollowUpStatusReport = 231
            FireFacilityRatingTrendReport = 232
            BMFacilityRatingTrendReport = 233
        End Enum
    End Class

    Partial Public Class rowTblMetaReport

        Public ReadOnly Property Vendor As TblMetaReportVendor.Vendors
            Get
                Return [Enum].Parse(GetType(TblMetaReportVendor.Vendors), colFldVendorId)
            End Get
        End Property

        'Public ReadOnly Property Parameters() As Dictionary(Of TblMetaParameter.Parameters, Object)
        '    Get
        '        Dim zDict As New Dictionary(Of TblMetaParameter.Parameters, Object)
        '        Dim zList As List(Of rowTblMetaSourceParameter) = TblMetaSourceParameter.LoadByIDX_IX_fldSourceId(colFldSourceId)
        '        For Each zItem As rowTblMetaSourceParameter In zList
        '            zDict.Add(zItem.colFldParameterId, "")
        '        Next
        '        Return zDict
        '    End Get
        'End Property

    End Class
End Namespace