'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ChartMasterPage

    '''<summary>
    '''ChartHeadContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChartHeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''lblClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClient As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TitleRowLeftContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TitleRowLeftContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''lblDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ParameterContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ParameterContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''MenuRowLeftContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuRowLeftContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''MenuRowCenterContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuRowCenterContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''lblTip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ChartContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChartContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''lblDisclaimer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDisclaimer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HiddenContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
