'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Grids_GridMasterPageLocationListings

    '''<summary>
    '''GridHeadContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridHeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''loader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loader As Global.GRC.Connect.Web.LoaderMsgCenter

    '''<summary>
    '''header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents header As Global.GRC.Connect.Web.Header

    '''<summary>
    '''divContainerContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContainerContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divTopInstructions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTopInstructions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTopMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTopMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divContainerActions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContainerActions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ContentPlaceHolder1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''Nav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nav As Global.GRC.Connect.Web.LeftNav

    '''<summary>
    '''divLocFavoritesLibrary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLocFavoritesLibrary As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''icoLibrary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents icoLibrary As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divLocExtractDownloadChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLocExtractDownloadChart As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''icoChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents icoChart As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divLocExtractDownloadReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLocExtractDownloadReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''icoReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents icoReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divLocExtractDownloadData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLocExtractDownloadData As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''icoExtractData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents icoExtractData As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divLocResetGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLocResetGrid As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''icoResetGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents icoResetGrid As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GridBodyContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridBodyContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''RevisionStampControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RevisionStampControl As Global.GRC.Connect.Web.RevisionStampControl

    '''<summary>
    '''HiddenContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''hidSIDParameter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidSIDParameter As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidMasterClientID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidMasterClientID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''FooterControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FooterControl As Global.GRC.Connect.Web.footer
End Class
