'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ClientConnectSite

    '''<summary>
    '''ClientConnectSiteHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientConnectSiteHead As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''ClientConnectSiteBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientConnectSiteBody As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''ClientConnectSiteBottomHtml control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientConnectSiteBottomHtml As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
